## Decide what each Claude Code hook answers, from fact hook event and git hand it.
##   Hook is mechanism and not rule: it calls koch verb and holds no rule of its own
##     (CURATOR.md, What no check can reach). Every finding here is one audit already states
##     for gate; this module reads hook's fact and names check holding it, so rule lives once.
##   Events, by verb argument: `path` refuses write outside branch scope; `edit` returns
##     static findings after write; `bash` refuses commit or push on `main` or outside grammar,
##     and rewrite of pushed history; `body` holds post before it lands to role line, footer,
##     Simplified Technical English counts, issue title and label, and pull request headings;
##     `stop` refuses end of turn that pushed or posted and lacks sign-off block; `start`
##     prints role, read order, carried list and drift; `push` and `msg` serve git hooks.
##   Pure functions take strings and return findings; procs read transcript JSON, since
##     `parseJson` is effectful.
##
##   Cost: hook reaches Claude Code session holding one repository alone, so CI stays gate.
##   Cost: `gitCommands` splits on shell operators by text, so `git` inside quoted string is
##     read as command; refusal then errs on safe side.
##   Cost: sign-off check reads shape, never whether row says anything; evidence cell of ✅
##     row must be non-empty and nothing more.

{.experimental: "strictFuncs".}

import std/[json, options, sequtils, strutils]
import ./[checker, commits, domains, english, findings, markdown, role, scope]


const
  EDIT_TOOLS* = ["Edit", "Write", "MultiEdit", "NotebookEdit"]
    ## Tools that write file; `path` runs before them and `edit` after.
  PULL_TOOLS* = ["mcp__github__create_pull_request", "mcp__github__update_pull_request"]
    ## Tools whose body is pull request body, which follows template rather than footer rule.
  WRITE_TOOLS* = [
    "mcp__github__add_issue_comment", "mcp__github__issue_write",
    "mcp__github__create_pull_request", "mcp__github__update_pull_request",
    "mcp__github__pull_request_review_write", "mcp__github__add_reply_to_pull_request_comment",
    "mcp__github__update_issue_comment", "mcp__github__add_comment_to_pending_review",
  ]
    ## GitHub tools that post; turn calling one ends with sign-off.
  FOOTER* = "_Generated by [Claude Code](https://claude.ai/code)_"
    ## Line every issue, comment and review ends with.
  SIGNOFF_HEADING* = "## Sign-off"
    ## Heading of closing block (GUIDE.md, Output contract).
  SIGNOFF_TABLE* = "| # | State | Item | Where | Evidence, or who acts |"
    ## Header row of its table, exact.
  SIGNOFF_LABELS* = ["**Role:**", "**Context:**", SIGNOFF_TABLE, "**Summary:**", "**Next step:**"]
    ## Parts of block, in order each must appear.
  MARKERS* = ["☑", "✅", "⚠", "⏸", "⬜"]
    ## State markers in sort order, variation selector stripped.
  SELECTOR = "️"
    ## Variation selector some markers carry; stripped before match.
  CARRIED_TAG = "(carried "
    ## Tag row carries for carried-list item.
  CARRIED_MAX* = 6
    ## Items on carried list (CONTRIBUTOR.md).
  MERGE_SUBJECT = "Merge "
    ## Opening of subject git writes for merge commit.
  PULL_HEADINGS* = ["## Intent", "## Scope", "## Verification", "## Record", "## Notes"]
    ## Headings pull request template gives.
  CHECK_MARK* = ".git/koch-check"
    ## File `koch check` writes tree hash it passed on, which `pre-push` reads.
  ROLE_WORD = "Role:"
    ## Word after bold marker in sign-off role line.


type
  Call* = object
    ## Define one tool call of turn, as transcript records it.
    name*: string     ## Tool name, such as `Bash` or `mcp__github__issue_write`.
    command*: string  ## Bash command text; empty for other tools.
    has_body*: bool   ## Input carried `body`, so GitHub write posted text.

  Turn* = object
    ## Define what transcript says about turn since last message of person.
    calls*: seq[Call]  ## Tool calls in order.
    text*: string      ## Text of last assistant message.


func isRoleString*(s: string): bool =
  ## Decide whether `s` is role string: `curator`, `curator/<project>` or
  ##   `contributor/<domain>/<project>`.
  let parts = s.split('/')
  case parts.len
  of 1: s == CURATOR
  of 2: parts[0] == CURATOR and parts[1].isProjectName
  of 3: parts[0] == CONTRIBUTOR and parts[1].findDomain.isSome and parts[2].isProjectName
  else: false


func insideRoot*(root, path: string): string =
  ## Read path relative to root; absolute path outside root is returned whole.
  let prefix = root.strip(leading = false, chars = {'/'}) & "/"
  if path.startsWith(prefix): path[prefix.len .. ^1] else: path


func checkEditPath*(branch, path: string): seq[Finding] =
  ## Report write outside scope branch names, before it happens.
  checkScope(branch, [path])


func gitCommands*(command: string): seq[seq[string]] =
  ## Read arguments of every `git` command in shell text, subcommand first.
  ##   Shell operators split segments; `-c key=value` and `-C dir` before subcommand are
  ##     skipped, so `git -c x=y push` reads as `push`.
  var text = command
  for op in ["&&", "||", ";", "|"]: text = text.replace(op, "\n")
  for segment in text.splitLines:
    let
      tokens = segment.splitWhitespace
      at = tokens.find("git")
    if at < 0: continue
    var i = at + 1
    while i < tokens.len and tokens[i].startsWith("-"):
      if tokens[i] in ["-c", "-C"]: inc i
      inc i
    result.add tokens[i .. ^1]


func checkBash*(branch, command: string, is_head_pushed: bool): seq[Finding] =
  ## Report commit or push on `main` or outside grammar, and rewrite of pushed history.
  for arguments in command.gitCommands:
    if arguments.len == 0: continue
    let sub = arguments[0]
    if sub in ["commit", "push"] and (branch == MAIN or branch.parseBranch.isNone):
      result.add finding(
        "", 0,
        "Never commit to `main`; push to branch inside grammar (CLAUDE.md); got `" & branch &
          "`.",
      )
    let is_forced = arguments.anyIt(it == "--force" or it == "-f" or it.startsWith("--force-"))
    if sub == "push" and is_forced:
      result.add finding("", 0, "Never rewrite pushed history (XI.2); got `git push --force`.")
    if is_head_pushed and ((sub == "commit" and "--amend" in arguments) or sub == "rebase"):
      result.add finding(
        "", 0, "Never rewrite pushed history (XI.2); HEAD is on remote; got `git " & sub & "`."
      )


func isPost*(tool: string, has_body: bool): bool =
  ## Decide whether tool call posts text: GitHub write tool whose input carries body.
  ##   Update of labels or draft state alone carries none, and has nothing to read.
  tool in WRITE_TOOLS and has_body


func outsideComments(text: string): string =
  ## Blank every HTML comment, so template left unfilled reads as empty.
  var rest = text
  while true:
    let open = rest.find(COMMENT_OPEN)
    if open < 0: break
    let close = rest.find("-->", open)
    if close < 0:
      rest = rest[0 ..< open]
      break
    rest = rest[0 ..< open] & rest[close + 3 .. ^1]
  rest


func checkBody*(
    tool, branch, title, body: string, labels: openArray[string], is_create: bool
): seq[Finding] =
  ## Report post that breaks what every post keeps, before it lands.
  let parsed = branch.parseBranch
  if parsed.isSome:
    let expected = ROLE_KEY & " " & parsed.get.roleName
    if body.roleLine != expected:
      result.add finding(
        "", 0, "Post must open with `" & expected & "`; got `" & body.roleLine.shortened & "`."
      )
  if tool notin PULL_TOOLS and not body.strip.endsWith(FOOTER):
    result.add finding("", 0, "Post must end with footer `" & FOOTER & "`; got no footer.")
  result.add englishFindings("post", body)
  if tool == "mcp__github__issue_write" and is_create:
    if title.parseSubject.isSome:
      result.add finding(
        "", 0, "Issue title is claim, never `type(scope):` subject; got `" & title & "`."
      )
    if not labels.anyIt(it.isRoleString):
      result.add finding(
        "", 0,
        "Issue must carry one role label, copied from grammar; got `" & labels.join(", ") & "`.",
      )
  if tool == "mcp__github__create_pull_request":
    let headings = body.headingLines
    for h in PULL_HEADINGS:
      if h notin headings:
        result.add finding("", 0, "Pull request body must carry `" & h & "`; got none.")
    let shown = body.section(PULL_HEADINGS[2]).outsideComments.strip
    if PULL_HEADINGS[2] in headings and shown.len == 0:
      result.add finding("", 0, "Verification must show change; got template comment alone.")


func carriedTags(cell: string): seq[int] =
  ## Read every `(carried N)` of cell as N; `0` where N is not digit.
  var at = cell.find(CARRIED_TAG)
  while at >= 0:
    let
      rest = cell[at + CARRIED_TAG.len .. ^1]
      close = rest.find(')')
      number = if close > 0: rest[0 ..< close].strip else: ""
    result.add(if number.len > 0 and number.allCharsInSet(Digits): number.parseInt else: 0)
    at = cell.find(CARRIED_TAG, at + 1)


func checkSignoff*(message, branch: string): seq[Finding] =
  ## Report message that lacks sign-off block, or holds it out of shape.
  let lines = message.splitLines
  var at = -1
  for i, line in lines:
    if line.strip == SIGNOFF_HEADING: at = i
  if at < 0:
    return @[finding(
      "", 0, "Turn that pushed or posted must end with `" & SIGNOFF_HEADING &
        "` block (GUIDE.md, Output contract); got none."
    )]
  let after = lines[at + 1 .. ^1]
  for line in after:
    if line.startsWith("#"):
      result.add finding("", 0, "Nothing follows sign-off; got heading `" & line & "`.")
  var
    starts: seq[int]
    pos = 0
  for label in SIGNOFF_LABELS:
    var found = -1
    for j in pos ..< after.len:
      if after[j].startsWith(label):
        found = j
        break
    if found < 0:
      result.add finding("", 0, "Sign-off lacks `" & label & "` in its order; got none.")
    else: pos = found + 1
    starts.add found
  if starts.anyIt(it < 0): return
  let
    role_text = after[starts[0]][SIGNOFF_LABELS[0].len .. ^1].strip.split(',')[0].strip
    parsed = branch.parseBranch
  if parsed.isSome and role_text != parsed.get.roleName:
    result.add finding(
      "", 0, "Sign-off role must be `" & parsed.get.roleName & "`; got `" & role_text & "`."
    )
  let rows = after[starts[2] + 1 ..< starts[3]].join("\n").tableRows
  var
    last = 0
    seen: seq[int]
  for i, row in rows:
    if row.len != 5:
      result.add finding("", 0, "Sign-off row must hold five cells; got `" & $row.len & "`.")
      continue
    if row[0] != $(i + 1):
      result.add finding(
        "", 0, "Sign-off rows are numbered from 1 in order; got `" & row[0] & "`."
      )
    let
      marker = row[1].replace(SELECTOR, "")
      state = MARKERS.find(marker)
    if state < 0:
      result.add finding(
        "", 0, "Sign-off state must be one of ☑️ ✅ ⚠️ ⏸️ ⬜; got `" & row[1] & "`."
      )
    elif state < last:
      result.add finding(
        "", 0, "Sign-off states sort ☑️ ✅ ⚠️ ⏸️ ⬜; got `" & row[1] & "` after later state."
      )
    else: last = state
    if state == 1 and row[4].len == 0:
      result.add finding(
        "", 0, "Sign-off ✅ row needs evidence; got empty cell in row " & row[0] & "."
      )
    for n in row[2].carriedTags:
      if n < 1 or n > CARRIED_MAX:
        result.add finding(
          "", 0, "Carried tag names item 1 to " & $CARRIED_MAX & "; got `" & $n & "`."
        )
      elif n in seen:
        result.add finding("", 0, "Carried item tagged twice; got `" & $n & "`.")
      else: seen.add n
  var k = starts[4] + 1
  while k < after.len and after[k].strip.len > 0: inc k
  for line in after[k .. ^1]:
    if line.strip.len > 0:
      result.add finding(
        "", 0, "Nothing follows Next step of sign-off; got `" & line.shortened & "`."
      )
  var prose: seq[string]
  for line in after:
    if line.strip.startsWith("|"): continue
    var text = line
    for label in SIGNOFF_LABELS:
      if text.startsWith(label): text = text[label.len .. ^1].strip
    prose.add text
  result.add englishFindings("sign-off", prose.join("\n"))


func checkPush*(recorded, pushed_tree: string): seq[Finding] =
  ## Report push of tree `koch check` did not pass on.
  if recorded.strip != pushed_tree.strip:
    result.add finding(
      "", 0,
      "`nim r koch check` must pass on exact commit pushed (CLAUDE.md); last green tree `" &
        recorded.strip & "`; got `" & pushed_tree.strip & "`.",
    )


func checkMessage*(
  branch, message: string, earlier: openArray[string], staged: openArray[string]
): seq[Finding] =
  ## Report commit breaking subject form, scope, ladder, body or record apart, before it lands.
  ##   Merge commit passes: git writes its subject, and commit check excludes merges upstream
  ##     (`commits.nim`), so duty to merge `main` into branch (CURATOR.md, duty 2) needs no
  ##     bypass of hook.
  ##   Comment lines git adds, and all below its scissors line, are dropped before body is read.
  var
    subject = ""
    body: seq[string]
  for line in message.splitLines:
    if line.startsWith("# ------------------------ >8"): break
    if line.startsWith("#"): continue
    if subject.len == 0:
      if line.strip.len > 0: subject = line.strip
    else: body.add line
  if subject.startsWith(MERGE_SUBJECT): return
  result = checkCommits(branch, @[subject] & @earlier)
  result.add checkBody(subject, body.join("\n"))
  result.add checkRecordCommit(subject, staged)


func startContext*(branch, contributor, carried_heading: string, drift: seq[Finding]): string =
  ## Compose text `start` adds to context: role, read order, grammar warning, drift, list.
  let parsed = branch.parseBranch
  var lines: seq[string]
  if parsed.isNone:
    lines.add "Branch `" & branch & "` is outside grammar; push to `curator/<name>`, " &
      "`curator/<project>/<name>` or `contributor/<domain>/<project>/<name>` (CLAUDE.md)."
  else:
    let prompt = if parsed.get.role == Role.Contributor: "CONTRIBUTOR.md" else: "CURATOR.md"
    lines.add "Role: " & parsed.get.roleName & ", on branch `" & branch & "`."
    lines.add "Read first: CONSTITUTION.md, STYLE.md, GLOSSARY.md, then " & prompt &
      ", then GUIDE.md."
  if drift.len > 0:
    lines.add "Base gained charter or checker your branch lacks; merge `origin/main` and " &
      "re-stamp (`check-drift`)."
  lines.add "Every turn that pushed or posted ends with `" & SIGNOFF_HEADING &
    "` (GUIDE.md, Output contract)."
  lines.add ""
  lines.add carried_heading
  lines.add contributor.section(carried_heading).strip
  lines.join("\n")


func turnWrites*(calls: openArray[Call]): bool =
  ## Decide whether turn pushed or posted: `git push` in Bash, or GitHub write with body.
  ##   Label or draft update carries no body and is no post, as `body` hook reads it.
  for c in calls:
    if isPost(c.name, c.has_body): return true
    if c.name == "Bash" and c.command.gitCommands.anyIt(it.len > 0 and it[0] == "push"):
      return true
  false


proc parseTurn*(transcript: string): Turn =
  ## Read tool calls since last message person wrote, and text of last assistant message.
  ##   Transcript is JSON lines; message of person is `user` entry holding text and no tool
  ##   result, since tool results arrive as `user` entries too.
  var entries: seq[JsonNode]
  for line in transcript.splitLines:
    if line.strip.len == 0: continue
    try: entries.add line.parseJson
    except JsonParsingError, ValueError: discard
  var start = 0
  for i, e in entries:
    if e{"type"}.getStr != "user": continue
    let content = e{"message", "content"}
    if content == nil: continue
    if content.kind == JString: start = i
    elif content.kind == JArray and
        content.getElems.anyIt(it{"type"}.getStr == "text") and
        not content.getElems.anyIt(it{"type"}.getStr == "tool_result"):
      start = i
  for e in entries[start .. ^1]:
    if e{"type"}.getStr != "assistant": continue
    let content = e{"message", "content"}
    if content == nil or content.kind != JArray: continue
    var text: seq[string]
    for item in content.getElems:
      case item{"type"}.getStr
      of "tool_use":
        result.calls.add Call(
          name: item{"name"}.getStr, command: item{"input", "command"}.getStr,
          has_body: item{"input", "body"} != nil,
        )
      of "text": text.add item{"text"}.getStr
      else: discard
    if text.len > 0: result.text = text.join("\n")
