## Hold markup of whole-cloth page, so it lives in file kind repository reads.
##
##   Page was drawn by hand as HTML; repository audit reads only registered file
##     kinds (Nim among them, HTML not), so markup is hosted here as one string
##     constant, and `design/wholecloth.nim` writes page from it.
##     Cost: audit cannot see inside string, so its five embedded comments (one
##       HTML header, one CSS banner, three SVG row labels) are kept telegraphic
##       by hand, and every line is kept within width by
##       `reflow_wholecloth.py`, which breaks lines only at whitespace that
##       rendering ignores: between tags, between attributes (hanging at two
##       spaces where nothing else fits), inside CSS, inside list-valued
##       attributes (`d`, `points`, `class`, `style`), and inside `aria-label`
##       prose, whose whitespace accessible-name computation collapses (checked:
##       accessibility trees of original and rebuilt page are equal).  One line,
##       turn ticks, held no whitespace to break at, so its character references
##       are decoded to characters, which parser does anyway (checked: DOM of
##       both pages equal outside turns panel, whitespace collapsed).  Never edit
##       reflowed lines by hand; rerun script.
##     Cost: one Google Fonts request is single URL wider than any line may be,
##       so `MARKUP` is three pieces joined at compile time around `FONTS_HREF`
##       rather than one literal.
##   Two marker lines stand where page's scripts were, each replaced by splicer
##     with one `<script>` element:
##       `{{turns_data}}`   -- body sim's sweeps, `var TURNS = ...;`, written by
##                            `design/turns.nim`, kept under `id="turns-sim"`.
##       `{{turns_script}}` -- turns panel program, `design/wholecloth_turns.nim`
##                            compiled for browser.
##   Not `&` format string: page is full of braces, so markers are plain text
##     found by `replace`.

{.experimental: "strictFuncs".}


const
  MARK_DATA* = "{{turns_data}}"
    ## Marker line standing where sim's data script goes.
  MARK_SCRIPT* = "{{turns_script}}"
    ## Marker line standing where panel program goes.
  FONTS_HREF = "https://fonts.googleapis.com/css2?" &
    "family=Fraunces:opsz,wght@9..144,500;9..144,600&" &
    "family=Instrument+Sans:wght@400;500;600&" &
    "family=Spline+Sans+Mono:wght@400;500&display=swap"
    ## Google Fonts request for page's three faces, joined from pieces (see header).


const MARKUP* = """<!--
  Hand-authored mock-up: ontology drawn afresh from agreed definitions (ODS
  vocabulary), keeping only accepted marks -- chevron-circle bodies, two arm
  inks with deep/plain shades for lead/follow, square/round hand shapes, and
  four level fills.
  Revision 3, after review: marks are fixed anchors on body, rope of mark's
  colour is that arm, and hand is wherever rope ends -- seam where two ropes
  meet is joined hands.  Every drawn state was asked of body sim
  (sim/verdicts.md, "from her away rest") and captions say what it answered.
  Low lock ends behind opposite shoulder, high lock behind its own; wrap ends
  at opposite front.  Not generated by workbench; proposal to react to.
-->
<title>Dance Ontology — Whole Cloth</title>
<link rel="stylesheet" href="""" & FONTS_HREF & """">
<style>
:root {
  --paper: #faf9f6; --card: #ffffff; --ink: #201f1c; --dim: #6d6a62;
  --faint: #9b968c; --rule: #ddd9d0; --rim: #c3bdb2; --wash: #f2efe8;
  --left: #3d7fd0; --right: #d0763d;
  --left-deep: #133a72; --right-deep: #723a13;
  --good: #3f7550; --no: #a84432; --hold-chip: #201f1c; --chip-text: #faf9f6;
  --display: "Fraunces", Georgia, "Times New Roman", serif;
  --body: "Instrument Sans", ui-sans-serif, system-ui, sans-serif;
  --mono: "Spline Sans Mono", ui-monospace, "SF Mono", Menlo, monospace;
}
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) {
  --paper: #16181b; --card: #1d2024; --ink: #e9e7e1; --dim: #a19d94;
  --faint: #7c7870; --rule: #33363b; --rim: #4c5057; --wash: #23262b;
  --left: #8fbdf2; --right: #f0a273;
  --left-deep: #3d77bd; --right-deep: #bd6a2c;
  --good: #6cab80; --no: #dd8a76; --hold-chip: #e9e7e1; --chip-text: #16181b;
} }
:root[data-theme="dark"] {
  --paper: #16181b; --card: #1d2024; --ink: #e9e7e1; --dim: #a19d94;
  --faint: #7c7870; --rule: #33363b; --rim: #4c5057; --wash: #23262b;
  --left: #8fbdf2; --right: #f0a273;
  --left-deep: #3d77bd; --right-deep: #bd6a2c;
  --good: #6cab80; --no: #dd8a76; --hold-chip: #e9e7e1; --chip-text: #16181b;
}

* { box-sizing: border-box; }
body { margin: 0; padding: 2.2rem 1.4rem 6rem; background: var(--paper);
  color: var(--ink); font: 16px/1.62 var(--body); }
.sheet { max-width: 64rem; margin: 0 auto; }

.kicker { font: 500 0.68rem/1 var(--mono); letter-spacing: 0.22em;
  text-transform: uppercase; color: var(--dim); margin: 0 0 0.8rem; }
h1 { font-family: var(--display); font-weight: 600;
  font-size: clamp(2rem, 5.4vw, 2.9rem); line-height: 1.02;
  letter-spacing: -0.015em; margin: 0 0 0.9rem; text-wrap: balance; }
.stand { color: var(--dim); max-width: 40rem; margin: 0; }
.stand b { color: var(--ink); font-weight: 600; }
header.top { display: flex; gap: 2.5rem; align-items: flex-start;
  flex-wrap: wrap; border-bottom: 2px solid var(--ink);
  padding-bottom: 1.8rem; }
header.top .words { flex: 1 1 21rem; }
header.top .specimen { flex: 1 1 24rem; max-width: 30rem; display: grid;
  grid-template-columns: 11rem 1fr; gap: 0.2rem 1rem; align-items: center; }
header.top .specimen svg { width: 100%; height: auto; display: block; }
.callouts { margin: 0; padding: 0; list-style: none; counter-reset: c;
  font: 400 0.7rem/1.45 var(--mono); color: var(--dim); }
.callouts li { counter-increment: c; position: relative; padding-left: 1.5rem;
  margin-top: 0.3rem; }
.callouts li::before { content: counter(c); position: absolute; left: 0;
  top: 0.12rem; width: 1.05rem; height: 1.05rem; border-radius: 50%;
  border: 1px solid var(--dim); text-align: center; line-height: 1.05rem;
  font-size: 0.62rem; color: var(--ink); }
.callouts b { color: var(--ink); font-weight: 500; }
header.top .speclabel { grid-column: 1 / -1; }
.badge circle { fill: var(--card); stroke: var(--dim); stroke-width: 0.9; }
.badge text { font: 500 6.4px var(--mono); fill: var(--ink);
  text-anchor: middle; }
.speclabel { font: 400 0.66rem/1.5 var(--mono); color: var(--dim);
  text-align: center; margin-top: 0.2rem; }
.speclabel b { color: var(--ink); font-weight: 500; }

section.plate { margin-top: 3.4rem; }
.pnum { font: 500 0.66rem/1 var(--mono); letter-spacing: 0.2em;
  text-transform: uppercase; color: var(--faint); }
section.plate h2 { font-family: var(--display); font-weight: 600;
  font-size: 1.45rem; letter-spacing: -0.01em; margin: 0.35rem 0 0.4rem;
  text-wrap: balance; }
section.plate > p { max-width: 42rem; margin: 0.4rem 0 0; }
section.plate > p, .panel p { color: var(--dim); }
section.plate p b, .panel p b { color: var(--ink); font-weight: 600; }
.m { font-family: var(--mono); font-size: 0.9em; }

.panel { border: 1px solid var(--rule); border-radius: 6px;
  background: var(--card); padding: 1.15rem 1.3rem 1.25rem;
  margin-top: 1.2rem; }
.panel h3 { margin: 0 0 0.2rem; font-size: 1.02rem; font-weight: 600; }
.panel h3 .tag { font: 500 0.6rem/1 var(--mono); letter-spacing: 0.14em;
  text-transform: uppercase; color: var(--right); margin-left: 0.55rem; }
.panel p { font-size: 0.885rem; max-width: 44rem; margin: 0.35rem 0 0; }

.figrow { display: flex; flex-wrap: wrap; gap: 1.3rem 1.6rem;
  margin-top: 1.1rem; align-items: flex-end; }
figure { margin: 0; text-align: center; }
figure svg { display: block; margin: 0 auto; }
figcaption { font: 400 0.68rem/1.5 var(--mono); color: var(--dim);
  margin-top: 0.35rem; }
figcaption b { color: var(--ink); font-weight: 500; }
figcaption .say { color: var(--faint); }
.figrow.tight figure { max-width: 18rem; }

.key { display: grid; grid-template-columns: auto 1fr; gap: 0.55rem 1rem;
  align-items: center; margin-top: 0.9rem; font-size: 0.875rem; }
.key svg { display: block; }
.key span { color: var(--dim); }
.key b { color: var(--ink); font-weight: 600; }

.note { margin-top: 1.2rem; padding: 0.85rem 1.1rem; background: var(--wash);
  border-left: 3px solid var(--rim); border-radius: 0 4px 4px 0;
  font-size: 0.875rem; }
.note p { margin: 0; color: var(--dim); max-width: 46rem; }
.note p + p { margin-top: 0.5rem; }
.note b { color: var(--ink); }

.notation { font: 400 0.8rem/1.9 var(--mono); background: var(--wash);
  border-radius: 5px; padding: 0.9rem 1.1rem; margin-top: 1.1rem;
  overflow-x: auto; }
.notation table { border-collapse: collapse; }
.notation td { padding: 0.05rem 1.3rem 0.05rem 0;
  vertical-align: top; }
.notation td:first-child { color: var(--faint); white-space: nowrap; }
.notation td:last-child { padding-right: 0; line-height: 1.5;
  padding-bottom: 0.45rem; }
.notation em { font-style: normal; color: var(--dim); }

table.ledger { border-collapse: collapse; font-size: 0.84rem;
  margin-top: 1.1rem; min-width: 34rem; }
.ledgerwrap { overflow-x: auto; }
table.ledger th { font: 500 0.62rem/1.4 var(--mono); letter-spacing: 0.08em;
  text-transform: uppercase; color: var(--faint); text-align: left;
  padding: 0.35rem 1.1rem 0.35rem 0; border-bottom: 1px solid var(--rule); }
table.ledger td { padding: 0.42rem 1.1rem 0.42rem 0;
  border-bottom: 1px solid var(--rule); color: var(--dim); }
table.ledger td.h { font: 500 0.8rem var(--mono); color: var(--ink);
  white-space: nowrap; }
table.ledger td.y { color: var(--good); font-weight: 600; }
table.ledger td.u { color: var(--faint); }
table.ledger td.rope { font-size: 0.78rem; max-width: 16rem; }

.verbs { display: grid; gap: 0.9rem;
  grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr));
  margin-top: 1.2rem; }
.verb { border: 1px solid var(--rule); border-radius: 6px;
  background: var(--card); padding: 0.8rem 1rem 0.9rem; }
.verb .term { font: 500 0.9rem var(--mono); }
.verb .term .k { font: 500 0.58rem/1 var(--mono); letter-spacing: 0.12em;
  text-transform: uppercase; color: var(--faint); margin-left: 0.5rem; }
.verb p { font-size: 0.82rem; color: var(--dim); margin: 0.3rem 0 0; }

.legend { display: flex; flex-wrap: wrap; gap: 0.5rem 1.4rem;
  align-items: center; margin-top: 0.7rem; font-size: 0.82rem;
  color: var(--dim); }
.legend svg { display: inline-block; vertical-align: -0.35em; }

.foot { margin-top: 3.6rem; border-top: 1px solid var(--rule);
  padding-top: 1.4rem; font-size: 0.9rem; color: var(--dim); max-width: 46rem; }
.foot b { color: var(--ink); }
.foot ul { margin: 0.6rem 0 0; padding-left: 1.2rem; }
.foot li { margin-top: 0.45rem; }

.specimen { --mark-bg: var(--paper); }
.panel, .verb { --mark-bg: var(--card); }
:root { --mark-bg: var(--paper); }
.cn.no { stroke: var(--no) !important; stroke-dasharray: 5 4; opacity: 0.8; }
.ctl { display: flex; flex-wrap: wrap; gap: 0.4rem 1.2rem; align-items: center;
  margin-top: 0.9rem; font: 400 0.72rem/1.4 var(--mono); color: var(--faint); }
.ctl .grp { display: flex; flex-wrap: wrap; gap: 0.3rem; align-items: center; }
.ctl button { font: 500 0.72rem/1 var(--mono); padding: 0.4rem 0.6rem; border-radius: 999px;
  border: 1px solid var(--rule); background: var(--card); color: var(--dim); cursor: pointer; }
.ctl button.on { background: var(--hold-chip); color: var(--chip-text); border-color:
  var(--hold-chip); }
.stagewrap { display: flex; flex-wrap: wrap; gap: 1rem 1.6rem; align-items: center; margin-top:
  0.8rem; }
.stagewrap svg { flex: 0 0 auto; width: 230px; height: auto; }
#readout { flex: 1 1 16rem; font: 400 0.8rem/1.7 var(--mono); color: var(--dim); }
#readout b { color: var(--ink); font-weight: 500; }
#readout b.ok { color: var(--good); } #readout b.bad { color: var(--no); }
.turnrow { margin-top: 0.4rem; }
.turnrow input { width: 100%; max-width: 40rem; display: block; }
.turnticks { display: flex; justify-content: space-between; max-width: 40rem;
  font: 400 0.66rem/1 var(--mono); color: var(--faint); padding: 0.2rem 0.3rem 0; }
.strip { display: flex; flex-wrap: wrap; gap: 0.6rem 0.25rem; margin-top: 1rem; }
.strip .mini { cursor: pointer; border-radius: 6px; padding: 0.3rem 0.1rem; border: 1px solid
  transparent;
  flex: 0 0 auto; width: 4.85rem; }
.strip .mini.limit { background: var(--wash); }
.strip .mini.blocked { cursor: default; }
.strip .mini.blocked .x { height: 76px; display: flex; align-items: center; justify-content: center;
  font: 500 1.4rem var(--mono); color: var(--no); }
.strip .mini:hover { border-color: var(--rule); background: var(--wash); }
.strip figcaption { font-size: 0.6rem; line-height: 1.35; }
.chip-l { fill: var(--card); }

/* figure strokes */
.rim  { fill: none; stroke: var(--rim); stroke-width: 2.2; }
.chev { fill: none; stroke: var(--rim); stroke-width: 1.8;
        stroke-linecap: round; stroke-linejoin: round; }
.cn   { fill: none; stroke-width: 3.4; stroke-linecap: round; }
.ghost{ fill: none; stroke-width: 2.4; stroke-linecap: round; opacity: 0.55; }
.callout { stroke: var(--faint); stroke-width: 1; fill: none; }
.lbl  { font: 9.5px var(--mono); fill: var(--dim); }
.axis { stroke: var(--rule); stroke-width: 1.4; }
.tick { stroke: var(--rim); stroke-width: 1.2; }
.dial-lbl { font: 10.5px var(--mono); fill: var(--faint); }
.chip-w { fill: var(--hold-chip); }
.chip-wt { font: 500 9.5px var(--mono); fill: var(--chip-text); }
.chip-l { fill: none; stroke: var(--dim); stroke-width: 1.2;
          stroke-dasharray: 3 2.4; }
.chip-lt { font: 9.5px var(--mono); fill: var(--dim); }
.refuse { font: 500 11px var(--mono); fill: var(--no); }
.gaugetxt { font: 10.5px var(--mono); fill: var(--dim); }

@media (prefers-reduced-motion: reduce) { * { animation: none !important; } }
</style>

<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs>
  <pattern id="aL" width="3" height="3" patternTransform="rotate(45)" patternUnits="userSpaceOnUse">
    <line x1="0" y1="0" x2="0" y2="3" stroke="var(--left)" stroke-width="1.4"/></pattern>
  <pattern id="aR" width="3" height="3" patternTransform="rotate(45)" patternUnits="userSpaceOnUse">
    <line x1="0" y1="0" x2="0" y2="3" stroke="var(--right)" stroke-width="1.4"/></pattern>
  <pattern id="aLd" width="3" height="3" patternTransform="rotate(45)"
    patternUnits="userSpaceOnUse">
    <line x1="0" y1="0" x2="0" y2="3" stroke="var(--left-deep)" stroke-width="1.4"/></pattern>
  <pattern id="aRd" width="3" height="3" patternTransform="rotate(45)"
    patternUnits="userSpaceOnUse">
    <line x1="0" y1="0" x2="0" y2="3" stroke="var(--right-deep)" stroke-width="1.4"/></pattern>
  <pattern id="aN" width="3" height="3" patternTransform="rotate(45)" patternUnits="userSpaceOnUse">
    <line x1="0" y1="0" x2="0" y2="3" stroke="var(--dim)" stroke-width="1.4"/></pattern>
</defs></svg>

<div class="sheet">

<header class="top">
  <div class="words">
    <p class="kicker">dance ontology · drawn afresh</p>
    <h1>Whole cloth</h1>
    <p class="stand">Everything agreed so far, redrawn from the ground up.
    Six ideas, in the order each one needs the last: the <b>marks</b>, the
    <b>heights</b>, the <b>holds</b>, the <b>modifiers</b> each arm can wear,
    the <b>turning</b> that writes them, and the <b>moves</b> between states.
    The accepted conventions are kept exactly — the chevron-circle body, the
    two arm inks with a deep shade for the lead, square against round, and
    the level fills. Everything else is re-derived from your definitions and
    marked for what it is: agreed, measured, or proposed.</p>
  </div>
  <div class="specimen">
    <svg viewBox="-60 -80 120 130" role="img"
      aria-label="An annotated couple: the lead behind the follow, both facing up. His Left mark
        stays at his side and his deep rope runs up the west side, round the outside of her left
        shoulder, to the joined hands at her left front; her right mark stays at her side and her
        orange rope hugs her front on the inner track to meet it.">
      <circle cx="0" cy="34" r="20" class="rim"/><polyline points="-5,38 0,30 5,38" class="chev"/>
      <circle cx="0" cy="-34" r="20" class="rim"/><polyline points="-5,-30 0,-38 5,-30"
        class="chev"/>
      <path d="M -20.0,26.3 L -29.5,-28.0 C -31.1,-36.9 -24.9,-38.0 -20.4,-45.8" class="cn"
        style="stroke:var(--left-deep)"/>
      <path d="M 20.0,-41.7 L 19.5,-43.1 L 19.0,-44.5 L 18.4,-46.0 L 17.8,-47.5 L 17.1,-48.9 L
        16.3,-50.3 L 15.3,-51.6 L 14.1,-52.7 L 12.8,-53.7 L 11.4,-54.6 L 9.9,-55.3 L 8.4,-55.9 L
        6.8,-56.5 L 5.3,-56.9 L 3.7,-57.2 L 2.0,-57.4 L 0.4,-57.5 L -1.3,-57.5 L -2.9,-57.3 L
        -4.5,-57.1 L -6.1,-56.7 L -7.7,-56.2 L -9.2,-55.6 L -10.7,-54.9 L -12.1,-54.1 L -13.5,-53.2
        L -14.8,-52.2 L -16.0,-51.2 L -17.2,-50.0 L -18.3,-48.8 L -19.3,-47.5 L -20.2,-46.1 L
        -20.4,-45.8" class="cn" style="stroke:var(--right)"/>
      <rect x="-26.0" y="28.0" width="12" height="12" rx="1.5"
        style="fill:var(--mark-bg);stroke:none"/><rect x="-26.0" y="28.0" width="12" height="12"
        rx="1.5" style="fill:var(--left-deep);stroke:var(--left-deep);stroke-width:1.5"/>
      <rect x="14.0" y="28.0" width="12" height="12" rx="1.5"
        style="fill:var(--mark-bg);stroke:none"/><rect x="14.0" y="28.0" width="12" height="12"
  rx="1.5" style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
      <circle cx="20.0" cy="-34.0" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="20.0"
        cy="-34.0" r="6" style="fill:var(--right);stroke:var(--right);stroke-width:1.5"/>
      <circle cx="-20.0" cy="-34.0" r="6" style="fill:var(--mark-bg);stroke:none"/><circle
        cx="-20.0" cy="-34.0" r="6" style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5"
        opacity="0.45"/>
      <g class="badge">
        <circle cx="-40" cy="34" r="5"/><text x="-40" y="36.2">1</text>
        <circle cx="-44" cy="0" r="5"/><text x="-44" y="2.2">2</text>
        <circle cx="-40" cy="-58" r="5"/><text x="-40" y="-55.8">3</text>
        <circle cx="10" cy="-70" r="5"/><text x="10" y="-67.8">4</text>
        <circle cx="40" cy="-38" r="5"/><text x="40" y="-35.8">5</text>
        <circle cx="42" cy="-10" r="5"/><text x="42" y="-7.8">6</text>
      </g>
      <path d="M -35,34 L -29,34 M -39,0 L -25,0 M -35,-57 L -24,-48 M 10,-65 L 4,-60 M 35,-37 L
        28,-35.5 M 37,-11 L 9,-31" class="callout"/>
    </svg>
    <ol class="callouts">
      <li><b>his Left</b>: the mark stays at his side; solid = low</li>
      <li><b>the deep rope</b> is his arm — straight where it can be, round the outside of her
        shoulder where it must</li>
      <li><b>the seam</b> is the joined hands: each rope ends where its hand is</li>
      <li><b>her right rope</b> hugs her front on the inner track: the wrap. Low means it passes
        <i>under</i> her other arm, which is free and so not drawn — only held arms are</li>
      <li><b>her right</b>: the mark fixed at her side, the fill saying low</li>
      <li><b>the chevron</b> is her facing: turned away, &#189; from face to face; rope model:
        holds</li>
    </ol>
    <p class="speclabel">the specimen — <b>Left to right-wrap-low @ &frac12;</b> — every mark on the
      page, once</p>
  </div>
</header>


<section class="plate">
  <p class="pnum">plate 1 · the marks</p>
  <h2>The conventions, kept exactly</h2>
  <p>These are settled, so everything after this plate is drawn in them and
  nothing restates them. A dancer is a circle with a chevron for the facing.
  A hand is its arm's ink — blue for left, orange for right — worn deep by
  the lead and plain by the follow; the lead's hands are squares, the
  follow's are rounds, so <b>ink says which arm, shade and shape say
  whose</b>. The fill on a hand is a height, defined on the next plate.</p>
  <div class="panel">
    <div class="key">
      <svg viewBox="0 0 44 26" width="44" height="26" aria-hidden="true">
        <circle cx="22" cy="13" r="11" class="rim"/>
        <polyline points="18,15.5 22,9.5 26,15.5" class="chev"/></svg>
      <span><b>a dancer</b> — the chevron is the facing; the rim is the body the arms go
        round</span>
      <svg viewBox="0 0 44 18" width="44" height="18" aria-hidden="true">
        <rect x="3" y="3" width="12" height="12" rx="1.5"
          style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.6"/>
        <circle cx="33" cy="9" r="6.5"
          style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.6"/></svg>
      <span><b>left arms</b> — blue; the lead's deep and square, the follow's plain and round.
      A mark is an arm's <b>anchor</b>, fixed at the body's side; it never moves</span>
      <svg viewBox="0 0 44 18" width="44" height="18" aria-hidden="true">
        <rect x="3" y="3" width="12" height="12" rx="1.5"
          style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.6"/>
        <circle cx="33" cy="9" r="6.5"
          style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.6"/></svg>
      <span><b>right arms</b> — orange, the same way round</span>
      <svg viewBox="0 0 52 18" width="52" height="18" aria-hidden="true">
        <line x1="3" y1="9" x2="20" y2="9"
          style="stroke:var(--left-deep);stroke-width:3.4;stroke-linecap:round"/>
        <line x1="20" y1="9" x2="37" y2="9"
          style="stroke:var(--right);stroke-width:3.4;stroke-linecap:round"/>
        <circle cx="44.5" cy="9" r="5"
          style="fill:none;stroke:var(--right);stroke-width:1.4"/></svg>
      <span><b>a connection</b> — two arms meeting end to end. The rope of a mark's colour
      <b>is that arm</b>, and <b>its end is the hand</b>; the seam where the two ropes meet is the
      joined hands, the deep rope always the lead's. Straight wherever it can be; it leaves a
      mark at its edge so the fill stays readable</span>
      <svg viewBox="0 0 44 18" width="44" height="18" aria-hidden="true">
        <circle cx="22" cy="9" r="6.5" style="fill:var(--mark-bg);stroke:none"/><circle cx="22"
  cy="9" r="6.5" style="fill:none;stroke:var(--left);stroke-width:1.6" opacity="0.45"/></svg>
      <span><b>faded</b> — a free hand: nobody holds it, but it keeps its identity. A free arm is
        never drawn; only a held arm has a rope</span>
    </div>
  </div>
</section>


<section class="plate">
  <p class="pnum">plate 2 · the heights</p>
  <h2>A level is a height, and nothing else</h2>
  <p>Your definitions place the three levels on the body itself: <b>low</b>
  is below the shoulder, about the torso; <b>high</b> is above it, about the
  neck; <b>above</b> clears the head. A level says where a connection rides
  — it says nothing about which arm passes over which; that is said by the
  drawing itself, on plate&nbsp;4. Because the pages are drawn from
  overhead, height is carried by the fill.</p>
  <div class="panel">
    <div class="figrow" style="align-items: center">
      <figure>
        <svg viewBox="0 0 336 158" width="400" role="img"
          aria-label="A side view of a dancer with three height bands: above over the head, high
            about the neck, low about the torso.">
          <line x1="14" y1="141" x2="320" y2="141" class="axis"/>
          <circle cx="58" cy="27" r="11" class="rim"/>
          <path d="M 58,38 L 58,48" class="rim"/>
          <rect x="45" y="48" width="26" height="54" rx="6" class="rim"/>
          <path d="M 52,102 L 50,140 M 64,102 L 66,140" class="rim"/>
          <path d="M 50,52 C 44,68 46,84 52,94" class="ghost" style="stroke: var(--rim); opacity:
            1"/>
          <circle cx="53" cy="97" r="4.5" style="fill:none;stroke:var(--rim);stroke-width:1.5"/>
          <line x1="88" y1="15" x2="320" y2="15" class="tick" stroke-dasharray="3 4"/>
          <line x1="88" y1="48" x2="320" y2="48" class="tick" stroke-dasharray="3 4"/>
          <text x="320" y="11" text-anchor="end" class="lbl">crown</text>
          <text x="320" y="60" text-anchor="end" class="lbl">shoulder</text>
          <rect x="96" y="1" width="12" height="12" rx="1.5"
            style="fill:url(#aN);stroke:var(--dim);stroke-width:1.4"/>
          <text x="116" y="10.5" class="gaugetxt">above — over the head</text>
          <rect x="96" y="24" width="12" height="12" rx="1.5"
            style="fill:none;stroke:var(--dim);stroke-width:1.4"/>
          <circle cx="102" cy="30" r="2.6" style="fill:var(--dim)"/>
          <text x="116" y="30" class="gaugetxt">high — above the shoulder,</text>
          <text x="116" y="42" class="gaugetxt">about the neck</text>
          <rect x="96" y="68" width="12" height="12" rx="1.5"
            style="fill:var(--dim);stroke:var(--dim);stroke-width:1.4"/>
          <text x="116" y="74" class="gaugetxt">low — below the shoulder,</text>
          <text x="116" y="86" class="gaugetxt">about the torso</text>
          <text x="116" y="108" class="lbl">a hand at rest hangs low —</text>
          <text x="116" y="119" class="lbl">so low is where states begin</text>
        </svg>
        <figcaption>the three bands, worn as fills on every hand</figcaption>
      </figure>
      <figure>
        <svg viewBox="0 0 200 120" width="200" aria-hidden="true">
          <g transform="translate(14,8)">
            <rect x="0" y="0" width="13" height="13" rx="1.5"
              style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.6"/>
            <text x="24" y="11" class="gaugetxt">hollow — height unsaid</text></g>
          <g transform="translate(14,36)">
            <rect x="0" y="0" width="13" height="13" rx="1.5"
              style="fill:var(--left-deep);stroke:var(--left-deep);stroke-width:1.6"/>
            <text x="24" y="11" class="gaugetxt">solid — low</text></g>
          <g transform="translate(14,64)">
            <rect x="0" y="0" width="13" height="13" rx="1.5"
              style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.6"/>
            <circle cx="6.5" cy="6.5" r="2.8" style="fill:var(--left-deep)"/>
            <text x="24" y="11" class="gaugetxt">dot — high</text></g>
          <g transform="translate(14,92)">
            <rect x="0" y="0" width="13" height="13" rx="1.5"
              style="fill:var(--mark-bg);stroke:none"/><rect x="0" y="0" width="13" height="13"
              rx="1.5" style="fill:url(#aLd);stroke:var(--left-deep);stroke-width:1.6"/>
            <text x="24" y="11" class="gaugetxt">hatched — above</text></g>
        </svg>
        <figcaption>the fills, unchanged</figcaption>
      </figure>
    </div>
    <p><b>Above is different in kind</b>, and the drawing says so: a hand
    above sits over the head — inside the circle — on the very axis the
    couple turns about. That placement is why plate&nbsp;5 will find it
    turning without limit, and why it can never wrap or lock.</p>
  </div>
</section>


<section class="plate">
  <p class="pnum">plate 3 · the holds</p>
  <h2>Six holds, each at its own rest</h2>
  <p>A hold names which hands are joined — nothing more. It is written
  <b>lead to follow</b>, case carrying who: <span class="m">Left to left</span>
  is the lead's Left holding the follow's left. Every hold is drawn at its
  <b>rest</b> — the orientation where nothing is wound. For the cross-name
  holds that is face to face; for the same-name holds it is <b>the follow
  turned away</b>, where the connection runs clean down one side. At rest,
  every connection is a straight line.</p>
  <div class="panel">
    <div class="figrow">
      <figure>
        <svg viewBox="-50 -58 100 116" width="128" role="img" aria-label="Left to left at rest:
          follow turned away, one straight connection on the west side.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <line x1="-20" y1="22.3" x2="-20" y2="0" class="cn" style="stroke:var(--left-deep)"/>
          <line x1="-20" y1="0" x2="-20" y2="-22.3" class="cn" style="stroke:var(--left)"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.5"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
          <circle cx="-20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5"/>
          <circle cx="20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="20"
            cy="-30" r="6" style="fill:none;stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left to left</b><br><span class="say">rest: follow away</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="128" role="img" aria-label="Right to right at rest:
          follow turned away, one straight connection on the east side.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <line x1="20" y1="22.3" x2="20" y2="0" class="cn" style="stroke:var(--right-deep)"/>
          <line x1="20" y1="0" x2="20" y2="-22.3" class="cn" style="stroke:var(--right)"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--left-deep);stroke-width:1.5" opacity="0.45"/>
          <circle cx="20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5"/>
          <circle cx="-20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="-20"
            cy="-30" r="6" style="fill:none;stroke:var(--left);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Right to right</b><br><span class="say">rest: follow away</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="128" role="img" aria-label="Left to right at rest:
          face to face, one straight connection on the west side.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <line x1="-20" y1="22.3" x2="-20" y2="0" class="cn" style="stroke:var(--left-deep)"/>
          <line x1="-20" y1="0" x2="-20" y2="-22.3" class="cn" style="stroke:var(--right)"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.5"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
          <circle cx="-20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5"/>
          <circle cx="20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="20"
            cy="-30" r="6" style="fill:none;stroke:var(--left);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left to right</b><br><span class="say">rest: facing</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="128" role="img" aria-label="Right to left at rest:
          face to face, one straight connection on the east side.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <line x1="20" y1="22.3" x2="20" y2="0" class="cn" style="stroke:var(--right-deep)"/>
          <line x1="20" y1="0" x2="20" y2="-22.3" class="cn" style="stroke:var(--left)"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--left-deep);stroke-width:1.5" opacity="0.45"/>
          <circle cx="20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5"/>
          <circle cx="-20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="-20"
            cy="-30" r="6" style="fill:none;stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Right to left</b><br><span class="say">rest: facing</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="128" role="img" aria-label="Both same-name holds at
          rest: follow away, two straight parallel connections.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <line x1="-20" y1="22.3" x2="-20" y2="0" class="cn" style="stroke:var(--left-deep)"/>
          <line x1="-20" y1="0" x2="-20" y2="-22.3" class="cn" style="stroke:var(--left)"/>
          <line x1="20" y1="22.3" x2="20" y2="0" class="cn" style="stroke:var(--right-deep)"/>
          <line x1="20" y1="0" x2="20" y2="-22.3" class="cn" style="stroke:var(--right)"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.5"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"/>
          <circle cx="-20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5"/>
          <circle cx="20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5"/>
        </svg>
        <figcaption><b>Left to left · Right to right</b><br><span class="say">rest: follow
          away</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="128" role="img" aria-label="Both cross-name holds at
          rest: facing, two straight parallel connections.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <line x1="-20" y1="22.3" x2="-20" y2="0" class="cn" style="stroke:var(--left-deep)"/>
          <line x1="-20" y1="0" x2="-20" y2="-22.3" class="cn" style="stroke:var(--right)"/>
          <line x1="20" y1="22.3" x2="20" y2="0" class="cn" style="stroke:var(--right-deep)"/>
          <line x1="20" y1="0" x2="20" y2="-22.3" class="cn" style="stroke:var(--left)"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.5"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"/>
          <circle cx="-20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5"/>
          <circle cx="20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5"/>
        </svg>
        <figcaption><b>Left to right · Right to left</b><br><span class="say">rest:
          facing</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="128" role="img" aria-label="Left to right and Right to
          left wound half a turn: the follow turned away, the two connections crossing in an X, the
          under one drawn broken.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <path d="M 20,22.3 Q 17,8 5,2.2" class="cn" style="stroke:var(--right-deep)"/>
          <path d="M -5,-2.2 Q -17,-8 -20,-22.3" class="cn" style="stroke:var(--left)"/>
          <path d="M -20,22.3 Q -16,6 0,0" class="cn" style="stroke:var(--left-deep)"/>
          <path d="M 0,0 Q 16,-6 20,-22.3" class="cn" style="stroke:var(--right)"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.5"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"/>
          <circle cx="-20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5"/>
          <circle cx="20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5"/>
        </svg>
        <figcaption><b>Left to right · Right to left @ &frac12;</b><br><span class="say">the X,
          follow away — broken line passes under</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="128" role="img" aria-label="Left to left and Right to
          right at face to face: the same X with the follow facing.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <path d="M 20,22.3 Q 17,8 5,2.2" class="cn" style="stroke:var(--right-deep)"/>
          <path d="M -5,-2.2 Q -17,-8 -20,-22.3" class="cn" style="stroke:var(--right)"/>
          <path d="M -20,22.3 Q -16,6 0,0" class="cn" style="stroke:var(--left-deep)"/>
          <path d="M 0,0 Q 16,-6 20,-22.3" class="cn" style="stroke:var(--left)"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.5"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"/>
          <circle cx="-20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5"/>
          <circle cx="20" cy="-30" r="6"
            style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5"/>
        </svg>
        <figcaption><b>Left to left · Right to right @ &frac12;</b><br><span class="say">the X,
          follow facing — a half turn from its away rest</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="128" role="img" aria-label="No hands joined: the free
          state.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--left-deep);stroke-width:1.5" opacity="0.45"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
          <circle cx="20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="20"
            cy="-30" r="6" style="fill:none;stroke:var(--left);stroke-width:1.5" opacity="0.45"/>
          <circle cx="-20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="-20"
            cy="-30" r="6" style="fill:none;stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>free</b><br><span class="say">four free hands</span></figcaption>
      </figure>
    </div>
    <div class="note">
      <p><b>Why the follow-away rest matters.</b> Drawn this way,
      <span class="m">Left to left</span> at rest is the same shape as
      <span class="m">Left to right</span> at rest — only her facing, and so
      which of her hands, differs. The two two-hand holds become one
      geometry offset by her facing: a half turn puts either pair in the X,
      with her <b>away</b> for the cross-name pair and <b>facing</b> for the
      same-name one. Neither X is a hold of its own. Counted from face to
      face the away rest is <b>@ &#8722;&#189;</b>; the body sim reads her
      arm there as open — the hand at her side — and as the low lock, led,
      only at the whole turn.</p>
      <p><b>The over/under in the X is the drawing's say.</b> The body sim
      finds the two arms of the X at the torso going round opposite sides of
      her, one across her front and one behind her back, so there is no
      crossing in plan for it to settle; above the head it counts the
      crossings and names which is over. The crossing break — the broken line passes under —
      is used <b>between two connections only</b>; two arms of one body say
      their over/under by track and fill, on the next plate.</p>
    </div>
  </div>
</section>


<section class="plate">
  <p class="pnum">plate 4 · the modifiers</p>
  <h2>What one arm can do, at its height</h2>
  <p>A modifier belongs to <b>one arm of one dancer</b> — either dancer —
  and it rides inside that hand's own name:
  <span class="m">Left-Lock-Low to right</span> is the lead's Left, locked
  low, holding the follow's right. Two drawing rules carry the anatomy.
  <b>An arm goes around the outside of the body circle</b>, leaving its
  mark at the angle that lets it hug the rim — only an <i>above</i> hand
  may sit inside, and never over the chevron. And <b>only a held arm is
  drawn</b>: under or over her other arm is said by the height and by how
  close the rope hugs the body — low and tight is under, high and wide is
  over — never by drawing the free arm. The mark never moves: what moves
  is the rope, and <b>the hand is where the rope ends</b> — a low lock ends
  just behind the <i>opposite</i> shoulder, a wrap at the opposite front,
  and a high lock comes back to its own shoulder: <b>a small loopback at
  the mark, on the facing side</b> — the elbow bends forward, never
  behind — the way a state loops to itself on an automaton. A connection
  is only ever drawn whole, hand to hand: an arm is never shown alone. Each
  figure was asked of the rope model; the turns count from face to
  face.</p>
  <div class="panel">
    <div class="figrow tight">
      <figure>
        <svg viewBox="-52 -62 104 124" width="150" role="img" aria-label="Left to left at its away
          rest: the follow turned away, one straight connection down the west side, no modifier.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/><circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26
            5,34" class="chev"/><path d="M -20,22.3 L -20,0" class="cn"
            style="stroke:var(--left-deep)"/><path d="M -20,0 L -20,-22.3" class="cn"
            style="stroke:var(--left)"/><rect x="-26.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26.0" y="24.0" width="12" height="12"
            rx="1.5" style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.5"/><rect
            x="14.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14.0" y="24.0" width="12" height="12"
            rx="1.5" style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"
            opacity="0.45"/><circle cx="-20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:none"/><circle cx="-20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5"/><circle cx="20.0"
            cy="-30.0" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="20.0" cy="-30.0"
            r="6" style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left to left</b><br><span class="say">open, at rest: the rope runs straight
          between the hands; sim: holds</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-52 -62 104 124" width="150" role="img" aria-label="Left to right-wrap-low at
          a half turn: the follow away, her right rope hugging her front on the inner track; his
          rope up the west side and round the outside of her left shoulder to meet it.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/><circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26
            5,34" class="chev"/><path d="M -20.0,22.3 L -29.5,-24.0 C -31.3,-32.8 -24.9,-34.0
            -20.4,-41.8" class="cn" style="stroke:var(--left-deep)"/><path d="M 20.0,-37.7 L
            19.5,-39.1 L 19.0,-40.5 L 18.4,-42.0 L 17.8,-43.5 L 17.1,-44.9 L 16.3,-46.3 L 15.3,-47.6
            L 14.1,-48.7 L 12.8,-49.7 L 11.4,-50.6 L 9.9,-51.3 L 8.4,-51.9 L 6.8,-52.5 L 5.3,-52.9 L
            3.7,-53.2 L 2.0,-53.4 L 0.4,-53.5 L -1.3,-53.5 L -2.9,-53.3 L -4.5,-53.1 L -6.1,-52.7 L
            -7.7,-52.2 L -9.2,-51.6 L -10.7,-50.9 L -12.1,-50.1 L -13.5,-49.2 L -14.8,-48.2 L
            -16.0,-47.2 L -17.2,-46.0 L -18.3,-44.8 L -19.3,-43.5 L -20.2,-42.1 L -20.4,-41.8"
            class="cn" style="stroke:var(--right)"/><rect x="-26.0" y="24.0" width="12" height="12"
            rx="1.5" style="fill:var(--mark-bg);stroke:none"/><rect x="-26.0" y="24.0" width="12"
            height="12" rx="1.5"
            style="fill:var(--left-deep);stroke:var(--left-deep);stroke-width:1.5"/><rect x="14.0"
            y="24.0" width="12" height="12" rx="1.5" style="fill:var(--mark-bg);stroke:none"/><rect
            x="14.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"
            opacity="0.45"/><circle cx="20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:none"/><circle cx="20.0" cy="-30.0" r="6"
            style="fill:var(--right);stroke:var(--right);stroke-width:1.5"/><circle cx="-20.0"
            cy="-30.0" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="-20.0" cy="-30.0"
            r="6" style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left to right-wrap-low @ &frac12;</b><br><span class="say">tight across her
          front, under her other arm; sim: holds, pressing</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-52 -62 104 124" width="150" role="img" aria-label="Left to right-wrap-high at
          a half turn: the same, her rope on the wide track over her other arm.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/><circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26
            5,34" class="chev"/><path d="M -20.0,22.3 L -29.5,-24.0 C -31.3,-32.8 -28.3,-36.0
            -23.8,-43.8" class="cn" style="stroke:var(--left-deep)"/><path d="M 20.0,-37.7 L
            19.6,-39.2 L 19.4,-40.8 L 19.3,-42.6 L 19.2,-44.5 L 18.9,-46.5 L 18.4,-48.5 L 17.6,-50.3
            L 16.5,-51.9 L 15.0,-53.1 L 13.3,-54.1 L 11.6,-54.9 L 9.8,-55.7 L 8.0,-56.3 L 6.2,-56.8
            L 4.3,-57.2 L 2.4,-57.4 L 0.5,-57.5 L -1.5,-57.5 L -3.4,-57.3 L -5.3,-57.0 L -7.1,-56.6
            L -9.0,-56.0 L -10.8,-55.3 L -12.5,-54.5 L -14.2,-53.6 L -15.8,-52.5 L -17.3,-51.4 L
            -18.8,-50.1 L -20.1,-48.7 L -21.4,-47.3 L -22.5,-45.8 L -23.6,-44.1 L -23.8,-43.8"
            class="cn" style="stroke:var(--right)"/><rect x="-26.0" y="24.0" width="12" height="12"
            rx="1.5" style="fill:var(--mark-bg);stroke:none"/><rect x="-26.0" y="24.0" width="12"
            height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.5"/><circle cx="-20.0"
            cy="30.0" r="2.7" style="fill:var(--left-deep)"/><rect x="14.0" y="24.0" width="12"
            height="12" rx="1.5" style="fill:var(--mark-bg);stroke:none"/><rect x="14.0" y="24.0"
            width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"
            opacity="0.45"/><circle cx="20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:none"/><circle cx="20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5"/><circle cx="20.0"
            cy="-30.0" r="2.7" style="fill:var(--right)"/><circle cx="-20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:none"/><circle cx="-20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left to right-wrap-high @ &frac12;</b><br><span class="say">wide across her
          front, over her other arm; sim: holds, led</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-52 -62 104 124" width="150" role="img" aria-label="Left to left-lock-low at a
          whole turn: the follow faces him, her rope round her back to just behind her opposite
          shoulder, his rope up the west side to meet it.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/><circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26
            5,34" class="chev"/><path d="M -20.0,22.3 L -29.5,-24.0 C -31.3,-32.8 -24.9,-34.0
            -20.4,-41.8" class="cn" style="stroke:var(--left-deep)"/><path d="M 20.0,-37.7 L
            19.5,-39.1 L 19.0,-40.5 L 18.4,-42.0 L 17.8,-43.5 L 17.1,-44.9 L 16.3,-46.3 L 15.3,-47.6
            L 14.1,-48.7 L 12.8,-49.7 L 11.4,-50.6 L 9.9,-51.3 L 8.4,-51.9 L 6.8,-52.5 L 5.3,-52.9 L
            3.7,-53.2 L 2.0,-53.4 L 0.4,-53.5 L -1.3,-53.5 L -2.9,-53.3 L -4.5,-53.1 L -6.1,-52.7 L
            -7.7,-52.2 L -9.2,-51.6 L -10.7,-50.9 L -12.1,-50.1 L -13.5,-49.2 L -14.8,-48.2 L
            -16.0,-47.2 L -17.2,-46.0 L -18.3,-44.8 L -19.3,-43.5 L -20.2,-42.1 L -20.4,-41.8"
            class="cn" style="stroke:var(--left)"/><rect x="-26.0" y="24.0" width="12" height="12"
            rx="1.5" style="fill:var(--mark-bg);stroke:none"/><rect x="-26.0" y="24.0" width="12"
            height="12" rx="1.5"
            style="fill:var(--left-deep);stroke:var(--left-deep);stroke-width:1.5"/><rect x="14.0"
            y="24.0" width="12" height="12" rx="1.5" style="fill:var(--mark-bg);stroke:none"/><rect
            x="14.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"
            opacity="0.45"/><circle cx="20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:none"/><circle cx="20.0" cy="-30.0" r="6"
            style="fill:var(--left);stroke:var(--left);stroke-width:1.5"/><circle cx="-20.0"
            cy="-30.0" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="-20.0" cy="-30.0"
            r="6" style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left to left-lock-low @ &#8722;1</b><br><span class="say">round her back to
          behind the opposite shoulder; sim: holds, led, blocked just past it</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-52 -62 104 124" width="150" role="img" aria-label="Left to left-lock-high at
          a whole turn: the follow faces him; her rope is a small loopback at her left mark on her
          facing side, hand to her own shoulder, and his rope curves across to meet the loop.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/><circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26
            5,34" class="chev"/><path d="M -20.0,22.3 L -20.0,6.0 C -20.0,-4.0 35.2,-19.7
            27.2,-15.7" class="cn" style="stroke:var(--left-deep)"/><path d="M 25.6,-27.9 L
            26.5,-27.6 L 27.3,-27.3 L 28.0,-26.8 L 28.7,-26.2 L 29.3,-25.6 L 29.8,-24.8 L 30.2,-24.0
            L 30.5,-23.2 L 30.7,-22.3 L 30.7,-21.4 L 30.7,-20.5 L 30.5,-19.7 L 30.2,-18.8 L
            29.8,-18.1 L 29.2,-17.3 L 28.6,-16.7 L 27.9,-16.1 L 27.2,-15.7 L 26.3,-15.3 L 25.5,-15.1
            L 24.6,-15.0 L 23.7,-15.0 L 22.8,-15.2 L 22.0,-15.4 L 21.2,-15.8 L 20.4,-16.3 L
            19.7,-16.8 L 19.1,-17.5 L 18.6,-18.2 L 18.2,-19.0 L 18.0,-19.9 L 17.8,-20.8 L 17.8,-21.6
            L 17.8,-22.5 L 18.0,-23.4 L 18.3,-24.2" class="cn" style="stroke:var(--left)"/><rect
            x="-26.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26.0" y="24.0" width="12" height="12"
            rx="1.5" style="fill:var(--mark-bg);stroke:var(--left-deep);stroke-width:1.5"/><circle
            cx="-20.0" cy="30.0" r="2.7" style="fill:var(--left-deep)"/><rect x="14.0" y="24.0"
            width="12" height="12" rx="1.5" style="fill:var(--mark-bg);stroke:none"/><rect x="14.0"
            y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"
            opacity="0.45"/><circle cx="20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:none"/><circle cx="20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:var(--left);stroke-width:1.5"/><circle cx="20.0"
            cy="-30.0" r="2.7" style="fill:var(--left)"/><circle cx="-20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:none"/><circle cx="-20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left to left-lock-high @ &#8722;1</b><br><span class="say">the loopback, on
          her facing side: hand to her own shoulder; sim: blocked before it, at &#8722;0.41, her arm
          against her own head</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-52 -62 104 124" width="150" role="img" aria-label="Left to left above, at the
          away rest: both ropes meet over her head, inside her circle and clear of the chevron.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/><circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26
            5,34" class="chev"/><path d="M -20.0,22.3 L -9.5,-37.0" class="cn"
            style="stroke:var(--left-deep)"/><path d="M -12.3,-30.0 L -9.5,-37.0" class="cn"
            style="stroke:var(--left)"/><rect x="-26.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26.0" y="24.0" width="12" height="12"
            rx="1.5" style="fill:url(#aLd);stroke:var(--left-deep);stroke-width:1.5"/><rect x="14.0"
            y="24.0" width="12" height="12" rx="1.5" style="fill:var(--mark-bg);stroke:none"/><rect
            x="14.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5"
            opacity="0.45"/><circle cx="-20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:none"/><circle cx="-20.0" cy="-30.0" r="6"
            style="fill:url(#aL);stroke:var(--left);stroke-width:1.5"/><circle cx="20.0" cy="-30.0"
            r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left to left @ above</b><br><span class="say">the hands over her head, clear
          of the chevron; sim: open at every turn</span></figcaption>
      </figure>
    </div>
    <p>What carries each fact: <b>the track</b> says lock or wrap (round the
    back, or across the front); <b>where the rope ends</b> says which lock
    (behind the opposite shoulder low; the loopback, forward, to its own shoulder high); <b>the
      fill</b> on the fixed
    mark says the height, and with it under or over — the track's width
    only repeats that. Nothing is written twice, so nothing can disagree.
    The turns in the captions count from face to face.</p>
  </div>

  <div class="panel">
    <h3>The budget, and the composite state<span class="tag">your assumption, kept</span></h3>
    <p>Your sheet enumerates <b>at most one modified arm per dancer, two
    across the couple</b>; two on one dancer is excluded until deemed
    necessary. A whole state is one name: the hold with each hand's
    modifier riding inside it. Both figures below were asked of the body
    sim — the first draft's version of the second (with her turned away)
    was <b>refused</b> by the rope model before it, and is gone; what the
    jointed-arm sim makes of each is in its caption.</p>
    <div class="figrow tight" style="align-items: flex-start; justify-content: space-around">
      <figure>
        <svg viewBox="-52 -62 104 124" width="150" role="img"
          aria-label="Left to left-lock-low: the follow faces him; her rope hugs her back from her
            fixed left mark to just behind her opposite shoulder, where his rope, up the west side
            and round the outside of that shoulder, meets it.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <path d="M -20.0,22.3 L -29.5,-24.0 C -31.3,-32.8 -24.9,-34.0 -20.4,-41.8" class="cn"
            style="stroke:var(--left-deep)"/>
          <path d="M 20.0,-37.7 L 19.5,-39.1 L 19.0,-40.5 L 18.4,-42.0 L 17.8,-43.5 L 17.1,-44.9 L
            16.3,-46.3 L 15.3,-47.6 L 14.1,-48.7 L 12.8,-49.7 L 11.4,-50.6 L 9.9,-51.3 L 8.4,-51.9 L
            6.8,-52.5 L 5.3,-52.9 L 3.7,-53.2 L 2.0,-53.4 L 0.4,-53.5 L -1.3,-53.5 L -2.9,-53.3 L
            -4.5,-53.1 L -6.1,-52.7 L -7.7,-52.2 L -9.2,-51.6 L -10.7,-50.9 L -12.1,-50.1 L
            -13.5,-49.2 L -14.8,-48.2 L -16.0,-47.2 L -17.2,-46.0 L -18.3,-44.8 L -19.3,-43.5 L
            -20.2,-42.1 L -20.4,-41.8" class="cn" style="stroke:var(--left)"/>
          <rect x="-26.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26.0" y="24.0" width="12" height="12"
            rx="1.5" style="fill:var(--left-deep);stroke:var(--left-deep);stroke-width:1.5"/>
          <circle cx="20.0" cy="-30.0" r="6" style="fill:var(--mark-bg);stroke:none"/><circle
  cx="20.0" cy="-30.0" r="6" style="fill:var(--left);stroke:var(--left);stroke-width:1.5"/>
          <rect x="14.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14.0" y="24.0" width="12" height="12"
  rx="1.5" style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
          <circle cx="-20.0" cy="-30.0" r="6" style="fill:var(--mark-bg);stroke:none"/><circle
            cx="-20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left to left-lock-low</b><br><span class="say">she faces him; hand behind her
          opposite shoulder; sim: holds, led, @ &#8722;1</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-52 -62 104 124" width="150" role="img"
          aria-label="Left-Lock-Low to left: the lead's rope hugs his back from his fixed Left mark
            to just behind his opposite shoulder; her rope comes down the east side, round the
            outside of that shoulder, to meet it. The follow faces him.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <path d="M 20.0,-22.3 L 29.5,24.0 C 31.3,32.8 24.9,34.0 20.4,41.8" class="cn"
            style="stroke:var(--left)"/>
          <path d="M -20.0,37.7 L -19.5,39.1 L -19.0,40.5 L -18.4,42.0 L -17.8,43.5 L -17.1,44.9 L
            -16.3,46.3 L -15.3,47.6 L -14.1,48.7 L -12.8,49.7 L -11.4,50.6 L -9.9,51.3 L -8.4,51.9 L
            -6.8,52.5 L -5.3,52.9 L -3.7,53.2 L -2.0,53.4 L -0.4,53.5 L 1.3,53.5 L 2.9,53.3 L
            4.5,53.1 L 6.1,52.7 L 7.7,52.2 L 9.2,51.6 L 10.7,50.9 L 12.1,50.1 L 13.5,49.2 L
            14.8,48.2 L 16.0,47.2 L 17.2,46.0 L 18.3,44.8 L 19.3,43.5 L 20.2,42.1 L 20.4,41.8"
            class="cn" style="stroke:var(--left-deep)"/>
          <rect x="-26.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26.0" y="24.0" width="12" height="12"
            rx="1.5" style="fill:var(--left-deep);stroke:var(--left-deep);stroke-width:1.5"/>
          <circle cx="20.0" cy="-30.0" r="6" style="fill:var(--mark-bg);stroke:none"/><circle
  cx="20.0" cy="-30.0" r="6" style="fill:var(--left);stroke:var(--left);stroke-width:1.5"/>
          <rect x="14.0" y="24.0" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14.0" y="24.0" width="12" height="12"
  rx="1.5" style="fill:var(--mark-bg);stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
          <circle cx="-20.0" cy="-30.0" r="6" style="fill:var(--mark-bg);stroke:none"/><circle
            cx="-20.0" cy="-30.0" r="6"
            style="fill:var(--mark-bg);stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>Left-Lock-Low to left</b><br><span class="say">only with her facing him: the
          sim holds it, led, with him turned a whole turn one way, and blocks before it the
          other</span></figcaption>
      </figure>
    </div>
    <div class="figrow" style="align-items: flex-start; gap: 1.2rem">
      <div class="notation" style="flex: 1 1 24rem; margin-top: 1.2rem"><table>
          <tr><td>a hold</td><td>Left to left<br><em>case says who</em></td></tr>
          <tr><td>a modified hand</td><td>Left-Lock-Low to right<br><em>the state rides in the
            hand's own name</em></td></tr>
          <tr><td>both modified</td><td>Left-Lock-High to right-wrap-low<br><em>one each, per the
            budget</em></td></tr>
          <tr><td>a position</td><td>Left to left @ &frac12;<br><em>the hold, turned from face to
            face</em></td></tr>
          <tr><td>shorthand</td><td>L–l · R–r<br><em>only where space is tight</em></td></tr>
        </table></div>
      <div class="note" style="flex: 1 1 18rem; margin-top: 1.2rem">
        <p><b>The safety edge, from your lock note:</b> a low lock is
        <b>entered from low</b>. Form it at the torso; never form the
        shape high and carry it down. It is a rule about the move, not
        the state — it belongs on the transition arrows of plate 6.</p>
      </div>
    </div>
  </div>
</section>


<section class="plate">
  <p class="pnum">plate 5 · turning</p>
  <h2>Turning is what writes the modifiers</h2>
  <p>A <b>position</b> is a hold turned some number of quarters, counted
  from face to face as the sheet counts; the same-name holds are drawn at
  their away rest, which sits a half turn along. And orientation is not decoration: turn the held
    dancer
  and the connection winds across her body, which is where wraps and locks
  come from. Your one worked row says it for
  <span class="m">Left to left</span> held low: <b>half a turn one way is
  the wrap; a whole turn the other way is the lock</b>.</p>
  <div class="panel">
    <div class="figrow">
      <figure>
        <svg viewBox="-50 -58 100 116" width="110" role="img" aria-label="At rest.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <circle cx="-20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="-20"
            cy="-30" r="6" style="fill:none;stroke:var(--left);stroke-width:1.5" opacity="0.45"/>
          <circle cx="20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="20"
            cy="-30" r="6" style="fill:none;stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--left-deep);stroke-width:1.5" opacity="0.45"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>@ &#8722;&frac12;</b> <span class="say">her away rest</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="110" role="img" aria-label="A quarter turn from
          rest.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-4,-35 4,-30 -4,-25"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <circle cx="0" cy="-50" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="0"
            cy="-50" r="6" style="fill:none;stroke:var(--left);stroke-width:1.5" opacity="0.45"/>
          <circle cx="0" cy="-10" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="0"
            cy="-10" r="6" style="fill:none;stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--left-deep);stroke-width:1.5" opacity="0.45"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>@ &#8722;&frac14;</b> <span class="say">a quarter on</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="110" role="img" aria-label="Half a turn from rest.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-34 0,-26 5,-34"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,34 0,26 5,34"
            class="chev"/>
          <circle cx="20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="20"
            cy="-30" r="6" style="fill:none;stroke:var(--left);stroke-width:1.5" opacity="0.45"/>
          <circle cx="-20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="-20"
            cy="-30" r="6" style="fill:none;stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--left-deep);stroke-width:1.5" opacity="0.45"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>@ 0</b> <span class="say">face to face — or @ &#8722;1,
          wound</span></figcaption>
      </figure>
      <figure>
        <svg viewBox="-50 -58 100 116" width="110" role="img" aria-label="Both dancers turned away
          from each other.">
          <circle cx="0" cy="-30" r="20" class="rim"/><polyline points="-5,-26 0,-34 5,-26"
            class="chev"/>
          <circle cx="0" cy="30" r="20" class="rim"/><polyline points="-5,26 0,34 5,26"
            class="chev"/>
          <circle cx="-20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="-20"
            cy="-30" r="6" style="fill:none;stroke:var(--left);stroke-width:1.5" opacity="0.45"/>
          <circle cx="20" cy="-30" r="6" style="fill:var(--mark-bg);stroke:none"/><circle cx="20"
            cy="-30" r="6" style="fill:none;stroke:var(--right);stroke-width:1.5" opacity="0.45"/>
          <rect x="14" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="14" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--left-deep);stroke-width:1.5" opacity="0.45"/>
          <rect x="-26" y="24" width="12" height="12" rx="1.5"
            style="fill:var(--mark-bg);stroke:none"/><rect x="-26" y="24" width="12" height="12"
            rx="1.5" style="fill:none;stroke:var(--right-deep);stroke-width:1.5" opacity="0.45"/>
        </svg>
        <figcaption><b>@ &frac12; · &frac12;</b> <span class="say">both turned
          away</span></figcaption>
      </figure>
    </div>
  </div>
  <div class="panel">
    <h3>The dial: one hold, turned, at each height</h3>
    <p>For <span class="m">Left to left</span>, turning the follow, counted
    <b>from face to face</b> — the sheet's own counting. Her away rest sits
    at &#8722;&#189;, where the sim reads her arm as open: the hand at her
    side, not yet behind her. Every row runs to two turns so its block
    shows. The words are the body sim's, read off the pose it found at
    each half turn; the legend below says how to read them. Mirror the
    whole dial for <span class="m">Right to right</span>.</p>
    <figure style="text-align:left; overflow-x:auto">
      <svg viewBox="0 0 700 236" width="700" style="max-width:100%; height:auto" role="img"
        aria-label="A dial of turns from face to face, two turns each way, one row per height. At
          low: open at minus one half, the lock led at minus one, blocked at minus one and an eighth
          by her arm against her own torso; the wrap way blocked at plus three tenths by his arm
          against his own torso. At high: the wrap led at minus one half, blocked at minus four
          tenths by her arm against her head; the lock led at plus one half and the wrap led at plus
          one, blocked at plus one and a quarter. Above: open at every turn, no block within two and
          a half.">
        <line x1="110" y1="34" x2="590" y2="34" class="axis"/>
        <g class="dial-lbl" text-anchor="middle"><line x1="110" y1="29" x2="110" y2="39"
          class="tick"/><text x="110" y="22">-2</text><line x1="170" y1="29" x2="170" y2="39"
          class="tick"/><text x="170" y="22">-1&#189;</text><line x1="230" y1="29" x2="230" y2="39"
          class="tick"/><text x="230" y="22">-1</text><line x1="290" y1="29" x2="290" y2="39"
          class="tick"/><text x="290" y="22">-&#189;</text><line x1="350" y1="29" x2="350" y2="39"
          class="tick"/><text x="350" y="22">face to face</text><line x1="410" y1="29" x2="410"
          y2="39" class="tick"/><text x="410" y="22">+&#189;</text><line x1="470" y1="29" x2="470"
          y2="39" class="tick"/><text x="470" y="22">+1</text><line x1="530" y1="29" x2="530"
          y2="39" class="tick"/><text x="530" y="22">+1&#189;</text><line x1="590" y1="29" x2="590"
          y2="39" class="tick"/><text x="590" y="22">+2</text></g>
        <text x="110" y="7" class="dial-lbl">&#8592; the lock way</text>
        <text x="590" y="7" class="dial-lbl" text-anchor="end">the wrap way &#8594;</text>

        <!-- low row -->
        <g transform="translate(0,76)">
          <rect x="12" y="-7" width="12" height="12" rx="1.5"
            style="fill:var(--dim);stroke:var(--dim)"/>
          <text x="32" y="3" class="gaugetxt">low</text>
          <text x="110" y="4" text-anchor="middle" class="refuse">&#10005;</text><text x="170" y="4"
            text-anchor="middle" class="refuse">&#10005;</text><rect x="201" y="-10" width="58"
            height="20" rx="10" class="chip-l"/><text x="230" y="4" text-anchor="middle"
            class="chip-lt">lock-low</text><circle cx="290" cy="0" r="3"
            style="fill:var(--rim)"/><circle cx="350" cy="0" r="3" style="fill:var(--rim)"/><rect
            x="357" y="-10" width="58" height="20" rx="10" class="chip-w"/><text x="386" y="4"
            text-anchor="middle" class="chip-wt">wrap-low</text><text x="470" y="4"
            text-anchor="middle" class="refuse">&#10005;</text><text x="530" y="4"
            text-anchor="middle" class="refuse">&#10005;</text><text x="590" y="4"
            text-anchor="middle" class="refuse">&#10005;</text>
          <path d="M 230,16 L 230,24 L 386,24 L 386,16" class="callout"/>
          <text x="320" y="37" text-anchor="middle" class="lbl">open at &#8722;&#189;, the lock led
            at &#8722;1, blocked at &#8722;1.12; the wrap pressing at +0.30 and blocked there, short
            of the half</text>
        </g>

        <!-- high row -->
        <g transform="translate(0,146)">
          <rect x="12" y="-7" width="12" height="12" rx="1.5"
            style="fill:none;stroke:var(--dim);stroke-width:1.4"/>
          <circle cx="18" cy="-1" r="2.6" style="fill:var(--dim)"/>
          <text x="32" y="3" class="gaugetxt">high</text>
          <text x="110" y="4" text-anchor="middle" class="refuse">&#10005;</text><text x="170" y="4"
            text-anchor="middle" class="refuse">&#10005;</text><text x="230" y="4"
            text-anchor="middle" class="refuse">&#10005;</text><rect x="261" y="-10" width="58"
            height="20" rx="10" class="chip-l"/><text x="290" y="4" text-anchor="middle"
            class="chip-lt">wrap-high</text><circle cx="350" cy="0" r="3"
            style="fill:var(--rim)"/><rect x="381" y="-10" width="58" height="20" rx="10"
            class="chip-l"/><text x="410" y="4" text-anchor="middle"
            class="chip-lt">lock-high</text><rect x="441" y="-10" width="58" height="20" rx="10"
            class="chip-l"/><text x="470" y="4" text-anchor="middle"
            class="chip-lt">wrap-high</text><text x="530" y="4" text-anchor="middle"
            class="refuse">&#10005;</text><text x="590" y="4" text-anchor="middle"
            class="refuse">&#10005;</text>
          <text x="350" y="30" text-anchor="middle" class="lbl">the lock way blocked at &#8722;0.41,
            her arm against her own head; the wrap way to 1&#188;, the names flipping past the half;
            every arm led, none pressing</text>
        </g>

        <!-- above row -->
        <g transform="translate(0,208)">
          <rect x="12" y="-7" width="12" height="12" rx="1.5"
            style="fill:url(#aN);stroke:var(--dim);stroke-width:1.4"/>
          <text x="32" y="3" class="gaugetxt">above</text>
          <line x1="160" y1="0" x2="118" y2="0" style="stroke:var(--dim);stroke-width:1.4"/>
          <path d="M 124,-4 L 116,0 L 124,4"
  style="fill:none;stroke:var(--dim);stroke-width:1.4;stroke-linecap:round;stroke-linejoin:round"/>
          <line x1="540" y1="0" x2="582" y2="0" style="stroke:var(--dim);stroke-width:1.4"/>
          <path d="M 576,-4 L 584,0 L 576,4"
  style="fill:none;stroke:var(--dim);stroke-width:1.4;stroke-linecap:round;stroke-linejoin:round"/>
          <text x="350" y="4" text-anchor="middle" class="dial-lbl">open at every turn to two and a
            half either way — the hand over her head turns with her</text>
        </g>
      </svg>
    </figure>
    <div class="legend">
      <span><svg viewBox="0 0 58 20" width="58" height="20"><rect x="0" y="0" width="58" height="20"
        rx="10" class="chip-w"/><text x="29" y="14" text-anchor="middle"
        class="chip-wt">wrap-low</text></svg>
      &nbsp;a solid marker: her arm <b style="color:var(--ink)">is</b> that modifier, pressing her
        body, and the pose holds</span>
      <span><svg viewBox="0 0 58 20" width="58" height="20"><rect x="0" y="0" width="58" height="20"
        rx="10" class="chip-l"/><text x="29" y="14" text-anchor="middle"
        class="chip-lt">lock-low</text></svg>
      &nbsp;a dashed marker: led — the hand is in the modifier's place, the arm clear of the
        body</span>
      <span><span class="refuse" style="font-family:var(--mono)">&#10005;</span>
      &nbsp;blocked: a joint at the end of its range, or an arm that would have to pass through
        somebody</span>
    </div>
    <div class="note">
      <p><b>Your floor test, put to the body sim.</b> You found that
      everything gets a full turn before it blocks, except the low wrap,
      which gets half — a full turn there leaves the partner no reach round
      the wrapping torso. Counted from face to face the sim agrees at the
      torso for the lock: <span class="m">Left to left</span> runs to 1.12
      the lock way, and hand to hand (<span class="m">Left to right</span>)
      blocks at 0.87. For the wrap it agrees on hand to hand — 0.56, the
      half — and disagrees on <span class="m">Left to left</span>, which it
      blocks at 0.30 with his shoulder's twist and her arm's reach across
      both at their edges. At the neck it gives a turn and more one way
      (1&#188; for Left to left, 1.06 for hand to hand) and under a half the
      other (0.41 and 0.65): the hands at neck height with the chests
      fourteen centimetres apart fold the elbows to their limit at rest,
      and one way of turning has nowhere to go from there. Above the head
      it agrees: no block within two and a half turns either way. Both
      hands held, it binds at the half turn (0.55) at the torso and the
      neck, as the ontology's capacity says. Every disagreement names a
      joint or a body, and the readout in the panel below says which at
      every turn; the model's limits — a rigid shoulder girdle, no trunk
      twist, one stance — are the first things to suspect.</p>
    </div>
  </div>

  <div class="panel" id="turns-panel">
    <h3>Every state, turned<span class="tag">the sim's poses, the page's drawing</span></h3>
    <p>Pick a starting hold and a height; drag the turn, or press play to
    sweep between the blocks. <b>What is drawn is the body sim's answer</b>:
    two bodies of the average adult's measurements and arms with a shoulder,
    an elbow and a wrist, each joint with the range a dancer tolerates. The
    sim turned every hold a fiftieth of a turn at a time, the arms carried on
    by small moves and settling into the most comfortable pose they could
    reach, and every moment of every sweep is on this page as data. Nothing
    here is the drawing's guess: every joint is where the sim put it, and the
    upper view is from above, the lower from the side. <b>The turn stops
    where a joint or a body refuses</b> &mdash; a shoulder or an elbow at the
    end of its range, an arm that would have to pass through somebody
    &mdash; and the readout names which. The small figures are every half
    turn, the two blocks included; a &#10005; is a half turn the arms will not
    reach. The words are the sim's at exactly that turn; <i>led</i> means the
    hand is there but the arm is not pressing the body.</p>
    <div class="ctl">
      <span class="grp" id="hold-buttons"></span>
      <span class="grp" id="level-buttons"></span>
      <span class="grp"><button id="play">play / pause</button><button id="to-rest">to
        rest</button></span>
    </div>
    <div class="stagewrap">
      <svg id="stage" viewBox="-60 -66 120 240" role="img" aria-label="The chosen hold at the chosen
        turn, from above and, below it, from the side."></svg>
      <div id="readout"></div>
    </div>
    <div class="turnrow">
      <input type="range" id="turn" min="-2" max="2" step="0.005" value="-0.5" aria-label="turn, in
        turns from the hold's rest">
      <div class="turnticks"><span>−2</span><span>−1½</span><span>−1</span><span>−½</span><span>face
        to face</span><span>+½</span><span>+1</span><span>+1½</span><span>+2</span></div>
    </div>
    <div class="strip" id="strip"></div>
  </div>
{{turns_data}}
{{turns_script}}
</section>


<section class="plate">
  <p class="pnum">plate 6 · the moves</p>
  <h2>Two primitives, four named compounds</h2>
  <p>Everything that changes what is held reduces to two primitives; the
  four starred helpers are worth their names because a lead thinks of each
  as one action. The starred ones keep contact through a trace — a hand
  travelling <b>on</b> the partner, not through the air. Definitions only
  for now: the symbols for these are deliberately unchosen, and the next
  round will offer candidates.</p>
  <div class="verbs">
    <div class="verb"><div class="term">collect <span class="k">primitive</span></div>
      <p>Join a connection: a lead hand takes a follow hand.</p></div>
    <div class="verb"><div class="term">drop <span class="k">primitive</span></div>
      <p>Release it: the connection ends, both hands go free.</p></div>
    <div class="verb"><div class="term">flick <span class="k">compound &#42;</span></div>
      <p>A drop with momentum: the hand is sent, not just let go.</p></div>
    <div class="verb"><div class="term">trace <span class="k">compound &#42;</span></div>
      <p>Slide a held connection along the partner's body: contact, moving.</p></div>
    <div class="verb"><div class="term">place <span class="k">compound &#42;</span></div>
      <p>Collect, then drop somewhere new — traced the whole way, with
      nothing in the path.</p></div>
    <div class="verb"><div class="term">cut <span class="k">compound &#42;</span></div>
      <p>Drop, then collect past an obstruction — an arm, torso, or neck in
      the way; the trace carries the contact over it.</p></div>
  </div>
  <div class="note">
    <p><b>Where the safety edge lives:</b> among these moves. Any move that
    would produce a <span class="m">…-Lock-Low</span> hand must arrive from
    a low carriage — collect low and turn, or trace down first. The state
    itself is fine; the forbidden thing is one particular way in.</p>
  </div>
</section>


<section class="plate">
  <p class="pnum">plate 7 · the ledger of trust</p>
  <h2>What is validated, what is only enumerated</h2>
  <p>Your sheet enumerates the whole space and has validated a corner of
  it. Two witnesses now exist — <b>you</b>, on the floor, and <b>the rope
  model</b>, in geometry — and this ledger keeps them apart so agreement
  means something. Shorthand hold names here, where the columns are
  tight.</p>
  <div class="panel">
    <div class="ledgerwrap">
    <table class="ledger">
      <tr><th>hold</th><th>all open</th><th>one lead arm</th><th>one follow arm</th><th>one arm
        each</th><th>the rope says</th></tr>
      <tr><td class="h">L–l</td><td class="y">&#10003;</td><td class="y">&#10003;</td><td
        class="y">&#10003;</td><td class="u">·</td>
        <td class="rope">agrees — lock at 1, wrap at &#189;; a full turn everywhere but the low
          wrap</td></tr>
      <tr><td class="h">R–r</td><td class="y">&#10003;</td><td class="y">&#10003;</td><td
        class="y">&#10003;</td><td class="u">·</td>
        <td class="rope">agrees, mirrored</td></tr>
      <tr><td class="h">L–r</td><td class="y">&#10003;</td><td class="u">·</td><td
        class="u">·</td><td class="u">·</td>
        <td class="rope">reaches wrap &amp; lock too — ahead of your validation</td></tr>
      <tr><td class="h">R–l</td><td class="y">&#10003;</td><td class="u">·</td><td
        class="u">·</td><td class="u">·</td>
        <td class="rope">likewise</td></tr>
      <tr><td class="h">L–l·R–r</td><td class="y">&#10003;</td><td class="u">·</td><td
        class="u">·</td><td class="u">·</td>
        <td class="rope">winds &#189; turn at low before the pair binds</td></tr>
      <tr><td class="h">L–r·R–l</td><td class="y">&#10003;</td><td class="u">·</td><td
        class="u">·</td><td class="u">·</td>
        <td class="rope">about &#189; turn likewise; more room above</td></tr>
    </table>
    </div>
    <p style="font-size:0.8rem"><span style="color:var(--good);font-weight:600">&#10003;</span>
    validated by you &nbsp;·&nbsp; <span style="color:var(--faint)">·</span>
    enumerated in the sheet, awaiting you &nbsp;—&nbsp; the rope column is
    the geometry's independent reading, never a substitute for yours.</p>
  </div>
</section>


<div class="foot">
  <p><b>Settled by your review, now drawn as policy:</b> the marks are
  fixed anchors and never move; the rope of a mark's colour is that arm and
  its end is the hand, the seam being the joined hands; straight runs
  wherever simple; every rope leaves a mark at its edge, at the angle that
  lets it hug the rim; arms round the outside of the body, an <i>above</i>
  hand inside but clear of the chevron; only held arms are drawn, under or
  over said by the height and the hug; the low lock ends behind the
  <i>opposite</i> shoulder and begins at the half turn, led; the high lock
  is a loopback to its own shoulder, on the facing side; a connection is
  drawn whole or not at all; same-name holds
  rest with the follow away, and turns count from face to face; the
  sheet's own naming — <span class="m">Left-Lock-Low to right</span> —
  with shorthand only where space is tight. <b>The turning panel on plate
  5 is now the body sim's</b> — jointed arms, the average adult's
  measurements, every moment of every sweep drawn as the sim found it —
  and the dial and the floor-test note above it were regenerated from the
  same sweeps; the still plates keep the drawing grammar as reviewed.</p>
  <p style="margin-top:0.9rem"><b>Still yours to pick or refuse:</b></p>
  <ul>
    <li>The <b>over/under in the X</b>: at the torso and the neck the sim
    finds the two arms going round opposite sides of her, so there is no
    crossing in plan to settle; above the head it counts the crossings
    and names which is over. The still plates keep the follow's-left rope
    under in both.</li>
    <li>Where the <b>sim and your floor disagree</b>, listed in the note
    under the dial: the Left-to-left wrap blocking at 0.30, the neck
    blocking under a half one way, hand to hand's lock short of the whole
    turn. Each names a joint at its edge; the model's rigid shoulder girdle
    is the first suspect.</li>
    <li>Whether the animated states on plate 5 read as you dance them —
    that panel is there to be checked against the floor, and its readout
    now says which joint is nearest its edge at every turn.</li>
    <li>Symbols for the six moves — withdrawn this round; candidates
    next.</li>
    <li>Still open, unchanged: whether an arm above ever blocks a turn,
    and both-modified dancers, excluded until needed.</li>
  </ul>
</div>

</div>
"""
  ## Whole page but its two scripts, ending in newline as file did; see header for markers.
