## Replicate hook decisions: scope before write, bash refusals, body shape, sign-off, push.

{.experimental: "strictFuncs".}

import std/[sequtils, strutils, unittest]
import ../../src/[findings, hooks]


const
  BRANCH = "contributor/ronri/pga_benchmark/gap-list"
  ROLE = "**Role:** contributor/ronri/pga_benchmark"
  SIGNOFF = """
Done.

## Sign-off

**Role:** contributor/ronri/pga_benchmark, `gap-list`

**State:** blocked, at `3f2a9c1`, pushed, #331 draft

| # | State | Item | Where | Evidence, or who acts |
| --- | --- | --- | --- | --- |
| 1 | ☑️ | Names stay by the ruling (carried 3) | #320 | the Architect ruled |
| 2 | ✅ | Gap list reads each baseline | `src/gaps.nim` | `koch check` green |
| 3 | ⚠️ | `koch drive` red in rga_visualiser | #332 | contributor/ronri/rga_visualiser, fix |
| 4 | ⏸️ | Names in the tests | #310 | D1 |
| 5 | ⬜ | cga5d baseline | `tests/` | this delegate |

**Context:** This branch adds the gap list. The Architect asked for baselines. #331 was a draft.

**Summary:** The gap list is done. Row 4 waits on D1.

**Decisions:**

**D1.** Keep the names `rga4d` and `cga5d` in the tests?
- Class: blocks this delegate
- Where: #310
- Options:
  - a. Keep: the tests stay as they are.
  - b. Rename: twelve suites change.
- Recommends: a, because both names are the names of the authority.
- Delay costs: #331 stays a draft.

**D2.** The cga5d baseline needs 16 GB, and the runner has 7 GB.
- Class: fact
- Where: #331

**Next step:** Architect: rule on D1 in #310.
"""
  PLAIN = """
## Sign-off

**Role:** contributor/ronri/pga_benchmark, `gap-list`

**State:** done, at `3f2a9c1`, pushed, #331 ready

| # | State | Item | Where | Evidence, or who acts |
| --- | --- | --- | --- | --- |
| 1 | ✅ | Gap list reads each baseline | `src/gaps.nim` | `koch check` green |

**Context:** This branch adds the gap list.

**Summary:** The gap list is done.

**Decisions:** None.

**Next step:** Architect: merge #331.
"""


func messages(found: seq[Finding]): seq[string] =
  ## Read messages of findings.
  found.mapIt(it.message)



suite "Hooks":
  test "role string grammar":
    check "curator".isRoleString and "curator/audit".isRoleString
    check "coordinator".isRoleString  # role with no branch
    check not "coordinator/library".isRoleString  # its own thread holds coordinator
    check "contributor/ronri/pga_benchmark".isRoleString
    check not "contributor/nowhere/x".isRoleString and not "owner".isRoleString
    check not "contributor/ronri/pga_benchmark/gap-list".isRoleString  # branch, not role


  test "path relative to root, and write outside scope refused":
    check insideRoot("/home/u/repo", "/home/u/repo/src/a.nim") == "src/a.nim"
    check insideRoot("/home/u/repo/", "/tmp/x") == "/tmp/x"
    check checkEditPath(BRANCH, "contributor/ronri/pga_benchmark/src/a.nim").len == 0
    check checkEditPath(BRANCH, "CONSTITUTION.md").len == 1  # outside project
    check checkEditPath("curator/x", "contributor/ronri/pga_benchmark/src/a.nim").len == 1
    check checkEditPath("curator/x", "contributor/ronri/pga_benchmark/GLOSSARY.md").len == 0


  test "git commands read through shell operators and options":
    check gitCommands("git -c a=b push -u origin x && echo ok") == @[@["push", "-u", "origin", "x"]]
    check gitCommands("cd x; git commit -m 'a' | cat") == @[@["commit", "-m", "'a'"]]
    check gitCommands("ls -la").len == 0


  test "bash refusals":
    check checkBash("main", "git commit -m x", false).messages[0].contains("Never commit to `main`")
    check checkBash("claude/tool-named", "git push -u origin claude/tool-named", false).len == 1
    check checkBash(BRANCH, "git push -u origin " & BRANCH, false).len == 0
    check checkBash(BRANCH, "git push --force", false).messages[0].contains("XI.2")
    check checkBash(BRANCH, "git push -f origin x", false).len == 1
    check checkBash(BRANCH, "git push --no-verify -u origin x", false).messages[0].contains(
      "duty 3",
    )  # pre-push hook skipped
    check checkBash(BRANCH, "git commit --no-verify -m x", false).len == 0  # push alone
    check checkBash(BRANCH, "git commit --amend --no-edit", true).len == 1  # pushed head
    check checkBash(BRANCH, "git commit --amend --no-edit", false).len == 0  # local head
    check checkBash(BRANCH, "git rebase origin/main", true).len == 1
    check checkBash(BRANCH, "git status", true).len == 0


  test "write without body is no post, so label-only update passes unread":
    check isPost("mcp__github__issue_write", has_body = true)
    check not isPost("mcp__github__issue_write", has_body = false)  # labels alone
    check not isPost("mcp__github__update_pull_request", has_body = false)  # draft toggle
    check not isPost("Read", has_body = true)  # not GitHub write tool


  test "body holds role line, footer, English and issue shape":
    const foot = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
    let good = ROLE & "\n\nOne short claim.\n" & foot
    check checkBody("mcp__github__add_issue_comment", BRANCH, "", good, [], false).len == 0
    let coordinator = "**Role:** coordinator\n\nOne short claim.\n" & foot
    check checkBody("mcp__github__add_issue_comment", "main", "", coordinator, [], false)
      .len == 0  # no branch holds coordinator, so none is compared
    let no_role = "Hello.\n" & foot
    check checkBody("mcp__github__add_issue_comment", BRANCH, "", no_role, [], false)
      .messages[0].contains("must open with `" & ROLE & "`")
    check checkBody("mcp__github__add_issue_comment", BRANCH, "", ROLE & "\n\nText.\n", [], false)
      .messages[0].contains("footer")
    let long = ROLE & "\n\n" & "word ".repeat(26).strip & ".\n" & foot
    check checkBody("mcp__github__add_issue_comment", BRANCH, "", long, [], false)
      .messages.anyIt("25 words" in it)
    let issue = checkBody(
      "mcp__github__issue_write",
      BRANCH,
      "fix(x): do thing",
      good,
      ["bug"],
      true,
    ).messages
    check issue.anyIt("claim" in it) and issue.anyIt("role label" in it)
    check checkBody("mcp__github__issue_write", BRANCH, "A claim", good, ["curator"], true).len == 0
    check checkBody("mcp__github__issue_write", BRANCH, "Any title", good, ["curator"], false)
      .len == 0  # update reads neither title nor labels
    check checkBody("mcp__github__issue_write", BRANCH, "A claim", good, ["coordinator"], true)
      .messages.anyIt("never `coordinator`" in it)  # brief carries label of role it starts
    check checkBody(
      "mcp__github__issue_write",
      BRANCH,
      "A claim",
      good,
      ["curator", "coordinator"],
      true,
    ).messages.anyIt("never `coordinator`" in it)  # no item is coordinator's
    check checkBody(
      "mcp__github__issue_write",
      BRANCH,
      "A claim",
      good,
      ["curator", "architect"],
      true,
    ).len == 0  # queue label beside role label


  test "pull request body keeps template headings and shows change":
    const head = ROLE & "\n\n## Intent\n\nX.\n\n## Scope\n\n- a\n\n"
    let shown =
      head & "## Verification\n\n<!-- t -->\nGreen.\n\n## Record\n\n- a\n\n## Notes\n\nNone.\n"
    check checkBody("mcp__github__create_pull_request", BRANCH, "t", shown, [], true).len == 0
    let unshown = head & "## Verification\n\n<!-- t -->\n\n## Record\n\n- a\n\n## Notes\n\nNone.\n"
    check checkBody("mcp__github__create_pull_request", BRANCH, "t", unshown, [], true)
      .messages.anyIt("show change" in it)
    let missing = head & "## Verification\n\nGreen.\n\n## Notes\n\nNone.\n"
    check checkBody("mcp__github__create_pull_request", BRANCH, "t", missing, [], true)
      .messages.anyIt("`## Record`" in it)


  test "sign-off shape":
    check checkSignoff(SIGNOFF, BRANCH).len == 0
    check checkSignoff(PLAIN, BRANCH).len == 0  # no decision
    check checkSignoff("Done.\n", BRANCH).messages[0].contains("must end with")
    check checkSignoff(SIGNOFF & "\n## After\n", BRANCH)
      .messages.anyIt("Nothing follows sign-off" in it)  # heading rule, not Next step rule
    check checkSignoff(SIGNOFF.replace("**Summary:**", "**Gist:**"), BRANCH)
      .messages.anyIt("lacks `**Summary:**`" in it)
    check checkSignoff(SIGNOFF.replace("**Role:** contributor/ronri", "**Role:** curator"), BRANCH)
      .messages.anyIt("role must be" in it)
    check checkSignoff(SIGNOFF.replace("| 2 | ✅ |", "| 2 | ⬜ |"), BRANCH)
      .messages.anyIt("sort" in it)  # ⬜ before ⚠️
    check checkSignoff(SIGNOFF.replace("| `koch check` green |", "| |"), BRANCH)
      .messages.anyIt("needs evidence" in it)
    check checkSignoff(SIGNOFF.replace("| 4 | ⏸️ |", "| 6 | ⏸️ |"), BRANCH)
      .messages.anyIt("numbered" in it)
    check checkSignoff(SIGNOFF.replace("(carried 3)", "(carried 9)"), BRANCH)
      .messages.anyIt("1 to 6" in it)
    check checkSignoff(SIGNOFF & "\nTrailing.\n", BRANCH)
      .messages.anyIt("Nothing follows Next step" in it)
    check checkSignoff(SIGNOFF.replace("| 2 | ✅ |", "| 2 | 🟢 |"), BRANCH)
      .messages.anyIt("one of" in it)


  test "sign-off parts come in order Architect set":
    const CONTEXT = "**Context:** This branch adds the gap list. The Architect asked for " &
      "baselines. #331 was a draft.\n\n"
    let context_first = SIGNOFF.replace(CONTEXT, "").replace("| # |", CONTEXT & "| # |")
    check checkSignoff(context_first, BRANCH)
      .messages.anyIt("lacks `**Context:**` in its order" in it)  # table comes first
    const SUMMARY = "**Summary:** The gap list is done. Row 4 waits on D1.\n\n"
    let summary_last = SIGNOFF.replace(SUMMARY, "").replace("**Next", SUMMARY & "**Next")
    check checkSignoff(summary_last, BRANCH)
      .messages.anyIt("lacks `**Decisions:**` in its order" in it)  # decisions follow summary


  test "sign-off state and decisions label":
    const STATE = "**State:** blocked, at `3f2a9c1`, pushed, #331 draft\n"
    check checkSignoff(SIGNOFF.replace(STATE, ""), BRANCH)
      .messages.anyIt("lacks `**State:**`" in it)
    check checkSignoff(SIGNOFF.replace("**State:** blocked", "**State:** stuck"), BRANCH)
      .messages.anyIt("state is one of" in it and "got `stuck`." in it)  # word, not branch
    check checkSignoff(SIGNOFF.replace("**State:** blocked,", "**State:** blocked"), BRANCH)
      .len == 0  # word ends at space too
    let unblocked = SIGNOFF.replace("- Class: blocks this delegate", "- Class: has a workaround: x")
    check checkSignoff(unblocked, BRANCH).messages.anyIt("exactly when" in it)  # blocked, no block
    check checkSignoff(unblocked.replace("**State:** blocked", "**State:** working"), BRANCH)
      .len == 0
    check checkSignoff(SIGNOFF.replace("**State:** blocked", "**State:** working"), BRANCH)
      .messages.anyIt("exactly when" in it)  # block, not blocked
    check checkSignoff(PLAIN.replace("**Decisions:** None.", "**Decisions:**"), BRANCH)
      .messages.anyIt("writes `**Decisions:** None.`" in it)
    check checkSignoff(SIGNOFF.replace("**Decisions:**\n", "**Decisions:** Two.\n"), BRANCH)
      .messages.anyIt("stands alone" in it)


  test "sign-off decision is card coordinator lifts unchanged":
    check checkSignoff(SIGNOFF.replace("**D2.**", "**D3.**"), BRANCH)
      .messages.anyIt("numbered from D1" in it)
    check checkSignoff(SIGNOFF.replace("- Class: fact\n", ""), BRANCH)
      .messages.anyIt("lacks `Class:`" in it)
    check checkSignoff(SIGNOFF.replace("- Where: #310\n", ""), BRANCH)
      .messages.anyIt("lacks `Where:`" in it)
    check checkSignoff(SIGNOFF.replace("- Class: fact", "- Class: urgent"), BRANCH)
      .messages.anyIt("Class is" in it)
    const OTHERS = "- Class: blocks this delegate and "
    check checkSignoff(
      SIGNOFF.replace("- Class: blocks this delegate", OTHERS & "the visualiser"), BRANCH
    ).messages.anyIt("role string; got `the visualiser`" in it)
    check checkSignoff(
      SIGNOFF.replace("- Class: blocks this delegate", OTHERS & "curator, curator/audit"), BRANCH
    ).len == 0


  test "sign-off decision offers two to four short options and picks one":
    check checkSignoff(SIGNOFF.replace("  - b. Rename: twelve suites change.\n", ""), BRANCH)
      .messages.anyIt("offers 2 to 4 options; got `1`" in it)
    const MORE = "  - c. Drop: x.\n  - d. Wait: x.\n  - e. Ask: x.\n- Recommends:"
    check checkSignoff(SIGNOFF.replace("- Recommends:", MORE), BRANCH)
      .messages.anyIt("offers 2 to 4 options; got `5`" in it)
    check checkSignoff(SIGNOFF.replace("a. Keep:", "a. Keep both names here:"), BRANCH)
      .messages.anyIt("at most 3 words" in it)
    check checkSignoff(SIGNOFF.replace("a. Keep:", "a. Keep the tests."), BRANCH)
      .messages.anyIt("`<letter>. <label>: <consequence>`" in it)  # no colon closes label
    check checkSignoff(SIGNOFF.replace("- Recommends: a,", "- Recommends: c,"), BRANCH)
      .messages.anyIt("Recommends names letter" in it)
    check checkSignoff(SIGNOFF.replace("- Recommends: a,", "- Recommends: a. Keep,"), BRANCH)
      .len == 0  # letter closed by period
    check checkSignoff(SIGNOFF.replace("- Recommends: a, because", "- Because"), BRANCH)
      .messages.anyIt("lacks `Recommends:`" in it)
    check checkSignoff(SIGNOFF.replace("in the tests?", "in the tests."), BRANCH)
      .messages.anyIt("ends with `?`" in it)
    let asks = SIGNOFF.replace("- Where: #331\n", "- Where: #331\n- Options:\n  - a. Buy: x.\n")
    check checkSignoff(asks, BRANCH).messages.anyIt("offers no option" in it)  # fact asks nothing
    let picks = SIGNOFF.replace("- Where: #331\n", "- Where: #331\n- Recommends: a\n")
    check checkSignoff(picks, BRANCH).messages.anyIt("picks no option" in it)


  test "sign-off rows name who acts":
    check checkSignoff(SIGNOFF.replace("| #310 | D1 |", "| #310 | the Architect rules |"), BRANCH)
      .messages.anyIt("names decision it waits on" in it)
    check checkSignoff(SIGNOFF.replace("| #310 | D1 |", "| #310 | D3 |"), BRANCH)
      .messages.anyIt("names decision it waits on" in it)  # no such decision
    check checkSignoff(SIGNOFF.replace("contributor/ronri/rga_visualiser, fix", "they fix"), BRANCH)
      .messages.anyIt("opens last cell with role string" in it)
    check checkSignoff(
      SIGNOFF.replace("contributor/ronri/rga_visualiser, fix", "outside, GitHub fixes runner"),
      BRANCH,
    ).len == 0


  test "push and commit message":
    check checkPush("abc\n", "abc").len == 0
    check checkPush("abc", "def").messages[0].contains("exact commit")
    check markPath("/repo", ".git") == "/repo/.git/koch-check"
    check markPath("/repo/wt", "/repo/.git/worktrees/wt") ==
      "/repo/.git/worktrees/wt/koch-check"  # worktree's own dir, where `.git` is file
    check checkMessage(BRANCH, "feat(pga_benchmark): add gaps\n\nBody.\n", [], []).len == 0
    check checkMessage(BRANCH, "Add gaps", [], []).len == 1  # not conventional
    check checkMessage(BRANCH, "Merge branch 'main' into " & BRANCH, [], []).len == 0  # git's own
    check checkMessage(
      BRANCH, "# comment\nfix(pga_benchmark): x", ["feat(pga_benchmark): y"], []
    ).len == 1  # fix without test before it
    # Body and staged paths reach commit check too, so hook says before commit lands.
    let wrapped = "feat(pga_benchmark): add gaps\n\nGaps read baseline of each\nalgebra.\n"
    check checkMessage(BRANCH, wrapped, [], []).messages.anyIt("runs on" in it)
    let staged =
      ["contributor/ronri/pga_benchmark/PROVENANCE.md", "contributor/ronri/pga_benchmark/a.nim"]
    check checkMessage(BRANCH, "docs(pga_benchmark): record gaps", [], staged).len == 1
    # Comment lines and everything below scissors are git's, never body.
    let verbose =
      "feat(pga_benchmark): add gaps\n# Please enter.\n# ------------------------ >8\ndiff x\n"
    check checkMessage(BRANCH, verbose, [], []).len == 0


  test "subject is first paragraph, as git reads it, and earlier subjects stay with check-commits":
    # Git joins lines before first blank line into subject, so line under subject is subject too.
    let joined = "feat(pga_benchmark): add gaps\nGaps read baseline of each algebra.\n"
    check checkMessage(BRANCH, joined, [], []).messages.anyIt("add gaps Gaps read" in it)
    # `--amend` runs hook while old head is still among earlier subjects.
    check checkMessage(BRANCH, "feat(pga_benchmark): add gaps\n", ["Old bad subject."], []).len == 0
    # Same bad subject written again is still new finding: one earlier copy cancels one.
    check checkMessage(BRANCH, "Old bad subject.\n", ["Old bad subject."], []).len > 0


  test "git command reads checkout it acts in, so worktree holds its own branch":
    check commandDirectory("git commit -m x", "/work/tree") == "/work/tree"
    check commandDirectory("git -C /other commit", "/work/tree") == "/other"
    check commandDirectory("git -C sub commit", "/work/tree") == "/work/tree/sub"
    check commandDirectory("cd /other && git push", "/work/tree") == "/other"
    check commandDirectory("cd \"sub\" && git -C deeper push", "/work") == "/work/sub/deeper"
    check commandDirectory("ls && git status", "/work") == "/work"


  test "start context and turn writes":
    let text = startContext(BRANCH, "## List\n\n1. one\n\n## Next\n", "## List", @[])
    check "Role: contributor/ronri/pga_benchmark" in text and "CONTRIBUTOR.md" in text
    check "1. one" in text and "## Sign-off" in text
    check "outside grammar" in startContext("claude/x", "", "## List", @[])
    check "re-stamp" in startContext("curator/x", "", "## List", @[finding("", 0, "d")])
    check isTurnWriting([Call(name: "Bash", command: "git push -u origin x")])
    check isTurnWriting([Call(name: "mcp__github__issue_write", has_body: true)])
    check not isTurnWriting([Call(name: "mcp__github__update_pull_request")])  # draft toggle
    check not isTurnWriting([Call(name: "Bash", command: "git status"), Call(name: "Read")])


  test "transcript parse finds calls since last message of person":
    const transcript =
      "{\"type\":\"user\",\"message\":{\"content\":[{\"type\":\"text\",\"text\":\"do it\"}]}}\n" &
      "{\"type\":\"assistant\",\"message\":{\"content\":[{\"type\":\"tool_use\"," &
      "\"name\":\"Bash\",\"input\":{\"command\":\"git push\"}}]}}\n" &
      "{\"type\":\"user\",\"message\":{\"content\":[{\"type\":\"tool_result\"," &
      "\"content\":\"ok\"}]}}\n" &
      "{\"type\":\"assistant\",\"message\":{\"content\":[{\"type\":\"text\"," &
      "\"text\":\"Done.\\n\\n## Sign-off\"}]}}\n"
    let turn = transcript.parseTurn
    check turn.calls.len == 1 and turn.calls[0].command == "git push"
    check turn.text.startsWith("Done.")
    check turn.calls.isTurnWriting
