## Replicate hook decisions: scope before write, bash refusals, body shape, sign-off, push.

{.experimental: "strictFuncs".}

import std/[sequtils, strutils, unittest]
import ../../src/hooks
import ../../src/findings


const
  BRANCH = "contributor/ronri/pga_benchmark/gap-list"
  ROLE = "**Role:** contributor/ronri/pga_benchmark"
  SIGNOFF = """
Done.

## Sign-off

**Role:** contributor/ronri/pga_benchmark, `gap-list` at `3f2a9c1`, pushed, #331 draft

**Context:** This branch adds the gap list. The Architect asked for baselines. #331 was a draft.

| # | State | Item | Where | Evidence, or who acts |
| --- | --- | --- | --- | --- |
| 1 | ☑️ | Names stay by the ruling (carried 3) | #320 | the Architect ruled |
| 2 | ✅ | Gap list reads each baseline | `src/gaps.nim` | `koch check` green |
| 3 | ⏸️ | Names in the tests | #310 | the Architect rules |
| 4 | ⬜ | cga5d baseline | `tests/` | this delegate |

**Summary:** The gap list is done. Row 3 waits on the Architect.

**Next step:** Architect: rule on #310.
"""


func messages(found: seq[Finding]): seq[string] =
  ## Read messages of findings.
  found.mapIt(it.message)


suite "Hooks":
  test "role string grammar":
    check "curator".isRoleString and "curator/audit".isRoleString
    check "contributor/ronri/pga_benchmark".isRoleString
    check not "contributor/nowhere/x".isRoleString and not "owner".isRoleString
    check not "contributor/ronri/pga_benchmark/gap-list".isRoleString  # branch, not role

  test "path relative to root, and write outside scope refused":
    check insideRoot("/home/u/repo", "/home/u/repo/src/a.nim") == "src/a.nim"
    check insideRoot("/home/u/repo/", "/tmp/x") == "/tmp/x"
    check checkEditPath(BRANCH, "contributor/ronri/pga_benchmark/src/a.nim").len == 0
    check checkEditPath(BRANCH, "CONSTITUTION.md").len == 1  # outside project
    check checkEditPath("curator/x", "contributor/ronri/pga_benchmark/src/a.nim").len == 1
    check checkEditPath("curator/x", "contributor/ronri/pga_benchmark/GLOSSARY.md").len == 0

  test "git commands read through shell operators and options":
    check gitCommands("git -c a=b push -u origin x && echo ok") == @[@["push", "-u", "origin", "x"]]
    check gitCommands("cd x; git commit -m 'a' | cat") == @[@["commit", "-m", "'a'"]]
    check gitCommands("ls -la").len == 0

  test "bash refusals":
    check checkBash("main", "git commit -m x", false).messages[0].contains("Never commit to `main`")
    check checkBash("claude/tool-named", "git push -u origin claude/tool-named", false).len == 1
    check checkBash(BRANCH, "git push -u origin " & BRANCH, false).len == 0
    check checkBash(BRANCH, "git push --force", false).messages[0].contains("XI.2")
    check checkBash(BRANCH, "git push -f origin x", false).len == 1
    check checkBash(BRANCH, "git push --no-verify -u origin x", false).messages[0].contains(
      "duty 3"
    )  # pre-push hook skipped
    check checkBash(BRANCH, "git commit --no-verify -m x", false).len == 0  # push alone
    check checkBash(BRANCH, "git commit --amend --no-edit", true).len == 1  # pushed head
    check checkBash(BRANCH, "git commit --amend --no-edit", false).len == 0  # local head
    check checkBash(BRANCH, "git rebase origin/main", true).len == 1
    check checkBash(BRANCH, "git status", true).len == 0

  test "write without body is no post, so label-only update passes unread":
    check isPost("mcp__github__issue_write", has_body = true)
    check not isPost("mcp__github__issue_write", has_body = false)  # labels alone
    check not isPost("mcp__github__update_pull_request", has_body = false)  # draft toggle
    check not isPost("Read", has_body = true)  # not GitHub write tool

  test "body holds role line, footer, English and issue shape":
    const FOOT = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
    let good = ROLE & "\n\nOne short claim.\n" & FOOT
    check checkBody("mcp__github__add_issue_comment", BRANCH, "", good, [], false).len == 0
    let no_role = "Hello.\n" & FOOT
    check checkBody("mcp__github__add_issue_comment", BRANCH, "", no_role, [], false)
      .messages[0].contains("must open with `" & ROLE & "`")
    check checkBody("mcp__github__add_issue_comment", BRANCH, "", ROLE & "\n\nText.\n", [], false)
      .messages[0].contains("footer")
    let long = ROLE & "\n\n" & "word ".repeat(26).strip & ".\n" & FOOT
    check checkBody("mcp__github__add_issue_comment", BRANCH, "", long, [], false)
      .messages.anyIt("25 words" in it)
    let issue = checkBody(
      "mcp__github__issue_write", BRANCH, "fix(x): do thing", good, ["bug"], true
    ).messages
    check issue.anyIt("claim" in it) and issue.anyIt("role label" in it)
    check checkBody("mcp__github__issue_write", BRANCH, "A claim", good, ["curator"], true).len == 0
    check checkBody("mcp__github__issue_write", BRANCH, "Any title", good, ["curator"], false)
      .len == 0  # update reads neither title nor labels

  test "pull request body keeps template headings and shows change":
    const HEAD = ROLE & "\n\n## Intent\n\nX.\n\n## Scope\n\n- a\n\n"
    let shown =
      HEAD & "## Verification\n\n<!-- t -->\nGreen.\n\n## Record\n\n- a\n\n## Notes\n\nNone.\n"
    check checkBody("mcp__github__create_pull_request", BRANCH, "t", shown, [], true).len == 0
    let unshown = HEAD & "## Verification\n\n<!-- t -->\n\n## Record\n\n- a\n\n## Notes\n\nNone.\n"
    check checkBody("mcp__github__create_pull_request", BRANCH, "t", unshown, [], true)
      .messages.anyIt("show change" in it)
    let missing = HEAD & "## Verification\n\nGreen.\n\n## Notes\n\nNone.\n"
    check checkBody("mcp__github__create_pull_request", BRANCH, "t", missing, [], true)
      .messages.anyIt("`## Record`" in it)

  test "sign-off shape":
    check checkSignoff(SIGNOFF, BRANCH).len == 0
    check checkSignoff("Done.\n", BRANCH).messages[0].contains("must end with")
    check checkSignoff(SIGNOFF & "\n## After\n", BRANCH).messages.anyIt("Nothing follows" in it)
    check checkSignoff(SIGNOFF.replace("**Summary:**", "**Gist:**"), BRANCH)
      .messages.anyIt("lacks `**Summary:**`" in it)
    check checkSignoff(SIGNOFF.replace("**Role:** contributor/ronri", "**Role:** curator"), BRANCH)
      .messages.anyIt("role must be" in it)
    check checkSignoff(SIGNOFF.replace("| 2 | ✅ |", "| 2 | ⬜ |"), BRANCH)
      .messages.anyIt("sort" in it)  # ⬜ before ⏸️
    check checkSignoff(SIGNOFF.replace("| `koch check` green |", "| |"), BRANCH)
      .messages.anyIt("needs evidence" in it)
    check checkSignoff(SIGNOFF.replace("| 3 | ⏸️ |", "| 5 | ⏸️ |"), BRANCH)
      .messages.anyIt("numbered" in it)
    check checkSignoff(SIGNOFF.replace("(carried 3)", "(carried 9)"), BRANCH)
      .messages.anyIt("1 to 6" in it)
    check checkSignoff(SIGNOFF & "\nTrailing.\n", BRANCH)
      .messages.anyIt("Nothing follows Next step" in it)
    check checkSignoff(SIGNOFF.replace("| 2 | ✅ |", "| 2 | 🟢 |"), BRANCH)
      .messages.anyIt("one of" in it)

  test "push and commit message":
    check checkPush("abc\n", "abc").len == 0
    check checkPush("abc", "def").messages[0].contains("exact commit")
    check markPath("/repo", ".git") == "/repo/.git/koch-check"
    check markPath("/repo/wt", "/repo/.git/worktrees/wt") ==
      "/repo/.git/worktrees/wt/koch-check"  # worktree's own dir, where `.git` is file
    check checkMessage(BRANCH, "feat(pga_benchmark): add gaps\n\nBody.\n", [], []).len == 0
    check checkMessage(BRANCH, "Add gaps", [], []).len == 1  # not conventional
    check checkMessage(BRANCH, "Merge branch 'main' into " & BRANCH, [], []).len == 0  # git's own
    check checkMessage(
      BRANCH, "# comment\nfix(pga_benchmark): x", ["feat(pga_benchmark): y"], []
    ).len == 1  # fix without test before it
    # Body and staged paths reach commit check too, so hook says before commit lands.
    let wrapped = "feat(pga_benchmark): add gaps\n\nGaps read baseline of each\nalgebra.\n"
    check checkMessage(BRANCH, wrapped, [], []).messages.anyIt("runs on" in it)
    let staged =
      ["contributor/ronri/pga_benchmark/PROVENANCE.md", "contributor/ronri/pga_benchmark/a.nim"]
    check checkMessage(BRANCH, "docs(pga_benchmark): record gaps", [], staged).len == 1
    # Comment lines and everything below scissors are git's, never body.
    let verbose =
      "feat(pga_benchmark): add gaps\n# Please enter.\n# ------------------------ >8\ndiff x\n"
    check checkMessage(BRANCH, verbose, [], []).len == 0

  test "start context and turn writes":
    let text = startContext(BRANCH, "## List\n\n1. one\n\n## Next\n", "## List", @[])
    check "Role: contributor/ronri/pga_benchmark" in text and "CONTRIBUTOR.md" in text
    check "1. one" in text and "## Sign-off" in text
    check "outside grammar" in startContext("claude/x", "", "## List", @[])
    check "re-stamp" in startContext("curator/x", "", "## List", @[finding("", 0, "d")])
    check turnWrites([Call(name: "Bash", command: "git push -u origin x")])
    check turnWrites([Call(name: "mcp__github__issue_write", has_body: true)])
    check not turnWrites([Call(name: "mcp__github__update_pull_request")])  # draft toggle
    check not turnWrites([Call(name: "Bash", command: "git status"), Call(name: "Read")])

  test "transcript parse finds calls since last message of person":
    const T =
      "{\"type\":\"user\",\"message\":{\"content\":[{\"type\":\"text\",\"text\":\"do it\"}]}}\n" &
      "{\"type\":\"assistant\",\"message\":{\"content\":[{\"type\":\"tool_use\"," &
      "\"name\":\"Bash\",\"input\":{\"command\":\"git push\"}}]}}\n" &
      "{\"type\":\"user\",\"message\":{\"content\":[{\"type\":\"tool_result\"," &
      "\"content\":\"ok\"}]}}\n" &
      "{\"type\":\"assistant\",\"message\":{\"content\":[{\"type\":\"text\"," &
      "\"text\":\"Done.\\n\\n## Sign-off\"}]}}\n"
    let turn = T.parseTurn
    check turn.calls.len == 1 and turn.calls[0].command == "git push"
    check turn.text.startsWith("Done.")
    check turn.calls.turnWrites
