## Lay out every frame position this project draws, card by card, for
## Architect to rule on.
##
##   Page exists to be argued with: each card carries identifier to quote
##     back, and mark saying whether it has been kept, dropped, or sent back
##     for mend.  Unmarked is unreviewed, never approved.
##   Verdict is given on picture, not on identifier.  So every ruled card's
##     drawing is pinned in `review.pins`, and build refuses to write page
##     whose ruled card has moved since: mend that reaches further than it
##     meant to stops here rather than shipping approval nobody gave.
##     Pins are regenerated by `tools/build.nim pins`, which is deliberate
##       second step -- verdict and pin are added together or not at all.
##   Sections `A` and `B` come from tables workbench already builds; `C` and
##     `D` are drawn here, and are only place project draws crossed pair's chain.

{.experimental: "strictFuncs".}

import std/[hashes, json, options, sequtils, strformat, strutils, tables]

import ./[page, parts]
import ../src/dance_ontology
import ../src/dance_ontology/draw/[figure, terms]


const PINS = staticRead("review-pins.json")
  ## What every ruled card's drawing was when it was ruled on.

const pinned = block:
  var held: Table[string, string]
  for pair in PINS.parseJson.pairs:
    held[pair.key] = pair.val.getStr
  held

const
  KEPT = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10",
          "A11", "A12", "A13", "A14", "A15", "A16", "A17",
          "B1", "B2", "B3", "B4", "B5", "B6", "B7",
          "B8", "B9", "B10", "B11", "B12", "B13", "B14",
          "B15", "B16", "B17", "B18", "B19", "B20", "B21",
          "B22", "B23", "B24", "B25", "B26", "B27", "B28",
          "C1", "C2", "C3", "C4", "C5", "C6", "C7",
          "D1", "D2", "D3", "D4", "D5", "D6", "D7",
          "E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8",
          "E9", "E10", "E11", "E12", "E13", "E14", "E15", "E16",
          "E17", "E18", "E19", "E20", "E21", "E22", "E23", "E24",
          "E25", "E26", "E27", "E28", "E29", "E30", "E31", "E32"]
    ## Ids Architect has confirmed accurate.  Added as they are ruled on.
  DROPPED: seq[string] = @[]
    ## Ids Architect has ruled out.
  FLAWED = initTable[string, string]()
    ## Position is right, drawing is not: kept, with what to mend.

func esc(s: string): string =
  s.multiReplace(("&", "&amp;"), ("<", "&lt;"), (">", "&gt;"))

const
  MANNER_SAID = {"fa": "follow turns", "la": "lead turns",
              "fo": "follow orbits", "lo": "lead orbits"}.toTable
    ## Workbench's tags said in words, since sheet is read by eye.
  QUARTER_SAID = ["none", "a quarter", "a half", "three quarters"]
    ## How far round that manner has gone, counted in quarter turns.
  QUARTER_FROM = ["the start", "a quarter", "a half", "three quarters"]
    ## Same, worded for move that sets off from it.

const QUARTER_WAY = wayName(wayOf(HalfTurns(QUARTER)))
  ## Which way round every quarter on this page turns.
  ##   Read off turn itself rather than written down, so label cannot
  ##     outlive sign it describes.

func said(tag: string; quarter: int): string =
  ## Name one manner of turn, how far it has gone, and which way round.
  if quarter == 0: &"{MANNER_SAID[tag]} {QUARTER_SAID[quarter]}"
  else: &"{MANNER_SAID[tag]} {QUARTER_SAID[quarter]} {QUARTER_WAY}"

func unpinned(svg: string): string =
  ## Take off pixel size workbench pins each figure to for its own rows, so
  ## card decides how big picture is drawn: inline style would beat sheet.
  result = svg
  const OPEN = " style=\"width: "
  let at = result.find(OPEN)
  if at < 0:
    return
  let shut = result.find('"', at + OPEN.len)
  if shut < 0:
    return
  result = result[0 ..< at] & result[shut + 1 .. ^1]

proc checkReview*() =
  ## Check every card ruled on has pin holding it to what it was drawn as.
  ##   Verdict without pin is verdict nothing guards, which is how ruled
  ##     card came to move under one in first place.
  for id in KEPT:
    doAssert id in pinned,
      &"A kept card carries no pin; run `tools/build.nim pins`: got `{id}`."
  for id in DROPPED:
    doAssert id in pinned,
      &"A dropped card carries no pin; run `tools/build.nim pins`: got `{id}`."


proc reviewParts*(): Parts =
  ## Collect every figure this page places: both walked pages' own parts,
  ## which it draws again at its own size.
  result = singleTurnParts()
  for key, svg in handTurnParts():
    result[key] = svg


func sheetOf(P: Parts): string =
  ## Build page, holding every card already ruled on to its own pin.

  func stepped(id: string; steps: seq[tuple[pick, note, svg: string]]): string =
    ## Stack several drawings in one cell, one shown at time, with button
    ## apiece.
    ##   Radio button and sibling rule do switching, so cell needs no script:
    ##     page stays markup browser can draw with nothing running.
    ##   Every step keeps its own note under its own picture, since note is
    ##     what tells one step from next.
    var
      picks = ""
      frames = ""
      buttons = ""
    for i, step in steps:
      let at = &"{id}-{i + 1}"
      picks.add &"""<input type="radio" name="{id}" id="{at}""" &
        (if i == 0: "\" checked>" else: "\">")
      frames.add &"""<div>{unpinned(step.svg)}""" &
        &"""<span class="step">{esc(step.note)}</span></div>"""
      buttons.add &"""<label for="{at}">{esc(step.pick)}</label>"""
    &"""{picks}<div class="frames">{frames}</div>""" &
      &"""<div class="picks">{buttons}</div>"""

  func card(id, label, note, art: string; drawings: seq[string];
            switching = false): string =
    ## Set one cell beside its identifier, carrying whatever has been ruled
    ## on it.  Unmarked is unreviewed, not approved.
    let
      flawed = id in FLAWED
      kept = id in KEPT
      dropped = id in DROPPED
      mark = if flawed: " flawed" elif kept: " kept"
             elif dropped: " dropped" else: ""
      badge = if flawed: """<em class="tag mend">mend</em>"""
              elif kept: """<em class="tag keep">kept</em>"""
              elif dropped: """<em class="tag drop">drop</em>"""
              else: ""
    # Verdict was given on pictures, so picture that moved under one carries
    # approval it was never given.  Card holds itself to what it was drawn
    # as when it was ruled on, and mend reaching further than it meant to
    # stops here rather than shipping.  Cell holding several drawings is
    # held to all of them, since verdict on it is verdict on all.
    if kept or dropped:
      doAssert $hash(drawings.join("")) == pinned.getOrDefault(id),
        &"A card already ruled on has been re-drawn: `{id}`.  Either the " &
          "mend is too wide, or that verdict has to go back."
    &"""<figure class="pic{mark}"><div class="art""" &
    (if switching: " steps" else: "") & &"""">{art}{badge}</div>""" &
    &"""<figcaption><code>{esc(id)}</code><b>{esc(label)}</b>""" &
    (if note.len > 0: &"""<span>{esc(note)}</span>""" else: "") &
    (if flawed: &"""<span class="fix">{esc(FLAWED[id])}</span>""" else: "") &
    "</figcaption></figure>"

  func card(id, label, note, svg: string): string =
    ## Set one drawing in cell of its own.
    card(id, label, note, unpinned(svg), @[unpinned(svg)])

  func card(id, label, note: string;
            steps: seq[tuple[pick, note, svg: string]]): string =
    ## Set several drawings in one cell, switched between by button.
    card(id, label, note, stepped(id, steps),
         steps.mapIt(unpinned(it.svg)), switching = true)

  var body = ""

  # `A`. Standard diagram: eight frames, two twist parities, and that is all of it.
  body.add """<section id="standard"><h2>A &middot; The standard diagram</h2>
  <p class="lede">Every picture the app, the review page, the frame map and the
  rotation axle draw is one of these. They are literally a table built at compile
  time. <b>The 148 rotation postures add no new one</b>: only the frame, whether
  the twist is odd or even, and &mdash; since this pass &mdash; which way it went
  reach the drawing, so level and contact are invisible here.</p>
  <p class="how"><b>It still cannot say which facing.</b> There are four
  &mdash; face-to-face, back-to-back, pillion lead, pillion follow &mdash; which
  is two bits, and <code>twist</code> carries one, its parity. So
  <code>isFacing(twist)</code> cannot tell face-to-face from back-to-back, nor
  pillion lead from pillion follow. The picture commits to one of each pair
  anyway: it draws the follow turned, never the lead. Every card below says the
  facing it draws, not the facing it knows.</p>
  <p class="how"><b>Each frame is counted from its own rest</b> &mdash; the
  facing where its connections run parallel and cross nothing. For a same-name
  pair that is <b>pillion lead</b>, not face to face, which is why A10 and A12
  read <i>at rest</i> and A9 and A11 read <i>half a turn from pillion lead</i>.
  The rest is measured by the same <code>phaseOf</code> the chain uses, never
  written down. A direction is named only where turning the other way draws a
  different picture, which is A16 and A17 alone.</p>
  <p class="how"><b>The break, and what it took to get it.</b> A crossing is
  broken by cutting the under arm at the middle &mdash; A9 does it, running one
  arm to (4.9,&nbsp;4.9) and resuming at (&minus;4.9,&nbsp;&minus;4.9). Which arm
  is cut is normally the frame's own <code>over</code> field. <b>A16 was the one
  picture whose lines crossed with neither of them cut</b>: its frame carries no
  <code>over</code>, because at rest those two connections run parallel and only
  turning the follow makes them cross. Which one ends up over depends on
  <b>which way</b> she turned, and the drawing was reducing the twist to odd or
  even before it drew &mdash; with a test asserting that a half turn each way
  drew the same picture. The sign now reaches the drawing, the test claims the
  opposite and can fail, and A16 carries its break. <b>A17 is what the other way
  round looks like</b>, and it is the only frame of the eight where turning the
  other way draws anything different.</p><div class="grid">"""
  func armFor(side: Side): Arm =
    ## Say which drawn arm this side of lead is.
    if side == Side.Left: Arm.L else: Arm.R

  func armFor(site: Site): Arm =
    ## Same for hand of follow.
    if site == Site.LeftHand: Arm.L else: Arm.R

  func restsFacing(target: Frame): bool =
    ## Say whether this frame rests face-to-face rather than pillion lead.
    ##   Hold rests where its two connections run parallel and cross
    ##     nothing, which for same-name pair is pillion lead and not face to
    ##     face (rule 31).  Measured by `phaseOf`, never written down.
    ##   Hold with fewer than two connections has no such state to be at, so
    ##     it is counted from face to face like everything else.
    if target.countHolds < 2:
      return true
    var holds: Holds
    for side in Side:
      if target.hold[side].isSome:
        holds[armFor(side)] = some armFor(target.hold[side].get)
    phaseOf(holds) < 1e-9

  proc facingNote(target: Frame; twist: int; way: string): string =
    ## Say which facing this picture draws, and what it is turned from.
    let
      drawn = if twist == 0: "face-to-face" else: "pillion lead"
      rest = if restsFacing(target): "face-to-face" else: "pillion lead"
    if drawn == rest: &"{drawn}, at rest"
    elif way.len > 0: &"{drawn}, half a turn {way} from {rest}"
    else: &"{drawn}, half a turn from {rest}"

  func turnShows(target: Frame): bool =
    ## Say whether turning one way draws anything other way does not.
    renderFrame(target, HalfTurns(1)) != renderFrame(target, HalfTurns(-1))

  for i, target in FRAMES:
    for twist in [0, 1]:
      let way = if twist == 1 and turnShows(target): "clockwise" else: ""
      body.add card(&"A{i * 2 + twist + 1}", describe(target),
                    facingNote(target, twist, way),
                    renderFrame(target, HalfTurns(twist)))
  # And other way round, wherever turning that way draws different picture.
  # Appended rather than interleaved, so every identifier already ruled on
  # still names picture it was ruled on.
  var also = FRAMES.len * 2
  for target in FRAMES:
    let widdershins = renderFrame(target, HalfTurns(-1))
    if widdershins == renderFrame(target, HalfTurns(1)):
      continue
    inc also
    body.add card(&"A{also}", describe(target),
                  facingNote(target, 1, "anticlockwise"), widdershins)
  body.add "</div></section>"

  # `B`. Single-hand turns: what animated page walks through.
  let st = P
  body.add """<section id="single"><h2>B &middot; Single-hand turn positions</h2>
  <p class="lede">What the single-hand turns page animates between. Sixty-four
  plates are drawn, but only twenty-eight are distinct pictures: two manners
  of turn that share a family share all four of their positions, and manners of
  different families share the one they rest at. Duplicates are folded here, and
  each card says which manners and quarters land on it. The four manners are the
  follow turning on the spot, the lead turning on the spot, the follow orbiting
  the lead, and the lead orbiting the follow; the quarter is how far round that
  manner has gone.</p>"""
  var n = 0
  for c in 0 ..< SINGLES.len:
    body.add &"""<h3>{esc(SINGLES[c].name)}</h3><div class="grid wide">"""
    var seen = initTable[string, string]()   # svg -> id already given it
    var order: seq[string]
    var whose = initTable[string, seq[string]]()
    for manner in Manner:
      for q in 0 ..< QUARTERS_ROUND:
        let key = &"st_{MANNERS[manner].tag}_{c}_{q}"
        if key notin st: continue
        let svg = st[key]
        if svg notin seen:
          inc n
          seen[svg] = &"B{n}"
          order.add svg
        whose.mgetOrPut(svg, @[]).add said(MANNERS[manner].tag, q)
    for svg in order:
      # Where every manner lands on one picture, say so once rather than four times.
      let who = if whose[svg].len == MANNERS.len and
                   QUARTER_SAID[0] in whose[svg][0]: "every manner, before it starts"
                else: whose[svg].join(" \u00B7 ")
      body.add card(seen[svg], SINGLES[c].name, who, svg)
    body.add "</div>"
  body.add "</section>"

  func windNote(note: string; wind: float; zero = ""): string =
    ## Say how far position stands from where its chain rests, and which way
    ## round.
    ##   Way comes from `wayOf`, so page and vocabulary cannot drift apart on
    ##     which sign is which.
    ##   `zero` replaces resting note for chain whose rest is not app's frame,
    ##     which `chainFor` names for hand-to-hand chain it was written for.
    if abs(wind) < 1e-9: (if zero.len > 0: zero else: note)
    else: note & " " & wayName(wayOf(HalfTurns(wind * 2)))


  # `C`. Chain two-hand page walks.
  let hh = P
  const PAIRED: Holds = [some Arm.L, some Arm.R]
  let
    dualPhase = phaseOf(PAIRED)
    dualChain = chainFor(PAIRED)
  # One scale for both chains, so section `C` and section `D` compare directly.
  var half = 0.0
  for position in CHAIN:
    half = max(half, extent(handPose(position.wind), captions = false))
  for position in dualChain:
    half = max(half, extent(posedAt(position.wind, dualPhase), captions = false))

  body.add """<section id="chain"><h2>C &middot; Hand-to-hand chain, face-to-face at rest</h2>
  <p class="lede">The seven places the two-hand hold stands, half a turn apart,
  which the hand-to-hand page animates along. These carry a wind as a real
  number, not a half-turn count, so the standard diagram cannot express any of
  them. Drawn at the same scale as section D below, so the two chains can be set
  against each other. The facing alternates along it &mdash; face-to-face at
  whole turns, pillion lead at halves. Each caption says how far round from the
  frame the position stands: <b>clockwise seen from above</b>, which is how the drawings see the
  couple, and which names the same turn whichever of the two dancers walks
  it.</p><div class="grid wide">"""
  for i, position in CHAIN:
    body.add card(&"C{i + 1}", position.name, windNote(position.note, position.wind),
      renderFigure("tiny", HAND_TO_HAND, ABOVE_BOTH, captions = false,
        pose = some handPose(position.wind), half = some half,
        twist = windTwist(position.wind), clear_marks = true))
  body.add "</div></section>"


  # `D`. Dual chain: same hold, follow starting away.
  body.add &"""<section id="paired"><h2>D &middot; Hand-to-hand chain, pillion lead at rest</h2>
  <p class="lede">The dual of section C: lead's left to follow's left, right to
  right. It walks the same chain read half a turn along, so it runs parallel
  <b>pillion lead</b> rather than face-to-face &mdash; this hold's phase measures
  {dualPhase} where the other's measures {HAND_PHASE}. Its facing alternates the
  other way about: pillion lead at whole turns, face-to-face at halves.
  No page in the project walks this chain; it is drawn here for the first
  time.</p><div class="grid wide">"""
  for i, position in dualChain:
    body.add card(&"D{i + 1}", position.name,
      windNote(position.note, position.wind,
             zero = "this hold's own parallel state"),
      renderFigure("tiny", PAIRED, ABOVE_BOTH, captions = false,
        pose = some posedAt(position.wind, dualPhase), half = some half,
        twist = windTwist(position.wind), clear_marks = true))
  body.add "</div></section>"

  # `E`. Every single-hand turn animated, edge by edge.
  body.add """<section id="single-moving"><h2>E &middot; Single-hand turns, moving</h2>
  <p class="lede">Every edge of section B, walked by every manner of turn. Each
  manner of each hold takes <b>two cells</b>: the whole round in one figure, and
  the same round a quarter at a time with a button per quarter. Both run at one
  pace, so the round's loop is simply four times an edge's. Unlike the positions,
  no two of these walks are the same picture &mdash; the walk differs even where
  the endpoints agree, and the lead's turns are told in the two stages rule 18
  asks for.</p>
  <p class="how"><b>Every walk here turns one way.</b> The page turns by
  <code>QUARTER</code>, which is a positive ninety degrees, so every walk here is
  clockwise. The four <i>positions</i> in section B are complete either way
  &mdash; four quarters is a whole round &mdash; but <b>the anticlockwise walks
  are not drawn at all</b>, and neither is any edge walked backwards. If this
  reference is to hold every move, that is a gap in it, not in the model.</p>
  <p class="how"><b>The chevron bend is a fault here, and nowhere above.</b> A
  reach is required to keep clear of both chevrons: <code>clearingMarks</code>
  walks each chevron as fourteen small discs and holds the reach off them by
  rule 22, so that a line through a mark always means that hand is held. In a
  still that is the rule doing its job, and every still in section B is right
  because of it. <b>In these animations it is what makes the motion catch</b>
  &mdash; the reach detours as it passes a chevron and snaps back after. The
  stills stay as drawn; the fix belongs to the walk, which makes it a question
  of how rule 22 should apply while moving rather than a repair to any
  picture.</p>"""
  var m = 0
  for c in 0 ..< SINGLES.len:
    body.add &"""<h3>{esc(SINGLES[c].name)}</h3><div class="grid wide">"""
    for manner in Manner:
      let
        tag = MANNERS[manner].tag
        said = &"{MANNER_SAID[tag]} {QUARTER_WAY}"
      if &"rd_{tag}_{c}" in st:
        inc m
        body.add card(&"E{m}", said, "the whole round, four quarters in one",
                      st[&"rd_{tag}_{c}"])
      var steps: seq[tuple[pick, note, svg: string]]
      for q in 0 ..< QUARTERS_ROUND:
        let key = &"tr_{tag}_{c}_{q}_{(q + 1) mod QUARTERS_ROUND}"
        if key notin st: continue
        steps.add ($(q + 1),
          &"quarter {q + 1} of 4: from {QUARTER_FROM[q]} to " &
            &"{QUARTER_FROM[(q + 1) mod QUARTERS_ROUND]}",
          st[key])
      if steps.len > 0:
        inc m
        body.add card(&"E{m}", said, "one quarter at a time", steps)
    body.add "</div>"
  body.add "</section>"

  func chainWay(manner: Manner): string =
    ## Say which way round this manner of turn walks chain.
    ##   Not same for all four: positive turn by lead unwinds what positive
    ##     turn by follow winds (rule 30), so each manner turns whichever way
    ##     carries pair inward along chain, and that sense is measured.
    wayName(wayOf(HalfTurns(HALF * windSense(manner))))


  # `F`. Every chain edge animated.
  body.add """<section id="chain-moving"><h2>F &middot; Hand-to-hand chain, moving</h2>
  <p class="lede">Every edge of section C, walked by every manner of turn. Each
  manner takes <b>two cells</b>: the whole chain in one figure &mdash; six half
  turns out from one swan to the other, and back, since the chain has ends and
  cannot close on itself &mdash; and the same chain an edge at a time with a
  button per edge. The whole-chain figure runs at the pace of its own edges,
  which makes it a long loop; say if it wants to be quicker. All four manners
  walk the same chain, since an orbit keeping its side to the centre winds the
  pair as far as it carries the walker. <b>They do not all turn the same way
  round</b>: a positive turn by the lead unwinds what a positive turn by the
  follow winds, so each manner turns whichever way carries the pair along the
  chain rather than off the end of it. Each caption says which, measured on the
  build.</p><div class="grid wide">"""
  var k = 0
  for manner in Manner:
    let
      tag = MANNERS[manner].tag
      said = &"{MANNER_SAID[tag]} {chainWay(manner)}"
    if &"hc_{tag}" in hh:
      inc k
      body.add card(&"F{k}", said,
                    &"the whole chain, {CHAIN.len - 1} halves out and back",
                    hh[&"hc_{tag}"])
    var steps: seq[tuple[pick, note, svg: string]]
    for i in 0 ..< CHAIN.len - 1:
      let key = &"hw_{tag}_{i}"
      if key notin hh: continue
      steps.add ($(i + 1), CHAIN[i].name & " to " & CHAIN[i + 1].name, hh[key])
    if steps.len > 0:
      inc k
      body.add card(&"F{k}", said, "one edge at a time", steps)
  body.add "</div></section>"

  const SWITCHING = block:
    ## Rules that show one step of switching cell and light its button.
    ##   Written out per step rather than by script: page is markup browser
    ##     draws with nothing running, and it stays that way.
    ##   Count follows longest walk on page, so cell of six steps cannot
    ##     quietly lose its last one.
    var css = ""
    for i in 1 .. max(QUARTERS_ROUND, CHAIN.len - 1):
      css.add &"  .steps input:nth-of-type({i}):checked ~ .frames > " &
        &"div:nth-child({i}) {{ display: block; }}\n"
      css.add &"  .steps input:nth-of-type({i}):checked ~ .picks > " &
        &"label:nth-child({i}) {{ background: var(--ink);" &
        " color: var(--card); border-color: var(--ink); }\n"
    css

  const HEAD = """<style>
  :root { --keep: #3f7550; --keep-wash: #eef4f0; --drop: #b3392a;
    --drop-wash: #f8efed; --mend: #a06a1e; --mend-wash: #f7f1e6;
    --mend-ink: #7a5016; }
  @media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) {
    --keep: #6cab80; --keep-wash: #1a2420; --drop: #e8705e;
    --drop-wash: #291c1a; --mend: #d9a45a; --mend-wash: #26200f;
    --mend-ink: #d7ab63; } }
  :root[data-theme="dark"] { --keep: #6cab80; --keep-wash: #1a2420;
    --drop: #e8705e; --drop-wash: #291c1a; --mend: #d9a45a;
    --mend-wash: #26200f; --mend-ink: #d7ab63; }
  .wrap { max-width: 72rem; margin: 0 auto; }
  .lede { color: var(--dim); max-width: 44rem; }
  .grid { display: grid; gap: .6rem; margin: 1rem 0 1.6rem;
    grid-template-columns: repeat(auto-fill, minmax(9.5rem, 1fr)); }
  .grid.wide { grid-template-columns: repeat(auto-fill, minmax(15rem, 1fr)); }
  .pic { margin: 0; background: var(--card); border: 1px solid var(--rule);
    border-radius: 3px; padding: .5rem; display: flex; flex-direction: column;
    gap: .4rem; }
  .pic .art { display: block; }
  .pic svg, .pic svg.tiny, .pic svg.mv { display: block; width: 100%;
    height: auto; }
  .pic figcaption { display: flex; flex-direction: column; gap: .1rem;
    font: .7rem/1.35 var(--sans); border-top: 1px solid var(--rule);
    padding-top: .35rem; }
  .pic code { font: .64rem var(--mono); color: var(--faint);
    letter-spacing: .04em; }
  .pic b { font-weight: 600; color: var(--ink); }
  .pic span { color: var(--dim); font: .64rem/1.3 var(--mono); }
  h2 { font-size: 1.05rem; letter-spacing: .01em; margin: 2.2rem 0 .3rem;
    padding-top: 1.1rem; border-top: 2px solid var(--rule-strong); }
  h3 { font-size: .78rem; text-transform: uppercase; letter-spacing: .1em;
    color: var(--faint); margin: 1.2rem 0 0; font-weight: 600; }
  h1 { font-size: 1.5rem; margin: 0 0 .3rem; }
  .how { background: var(--wash); border-left: 3px solid var(--rule-strong);
    padding: .8rem 1rem; margin: 1.2rem 0 0; max-width: 44rem;
    font-size: .88rem; color: var(--dim); }
  .how b { color: var(--ink); }
  .tally { font: .82rem var(--mono); color: var(--dim); margin: .6rem 0 0; }
  .tally b { color: var(--ink); }
  .pic .art { position: relative; }
  .tag { position: absolute; top: 0; right: 0; font: 600 .58rem/1 var(--sans);
    text-transform: uppercase; letter-spacing: .08em; padding: .2rem .3rem;
    border-radius: 2px; font-style: normal; }
  .tag.keep { background: var(--keep); color: var(--card); }
  .tag.drop { background: var(--drop); color: var(--card); }
  .pic.kept { border-color: var(--keep); background: var(--keep-wash); }
  .pic.dropped { border-color: var(--drop); background: var(--drop-wash); }
  .pic.dropped .art svg { opacity: .38; }
  .tag.mend { background: var(--mend); color: var(--card); }
  .pic.flawed { border-color: var(--mend); background: var(--mend-wash); }
  .pic .fix { color: var(--mend-ink); font: .62rem/1.35 var(--sans); }
  .pic { overflow: hidden; }
  .steps > input { position: absolute; width: 1px; height: 1px; opacity: 0; }
  .frames > div { display: none; }
  .frames span.step { display: block; color: var(--dim); margin-top: .25rem;
    font: .6rem/1.3 var(--mono); }
  .picks { display: flex; flex-wrap: wrap; gap: .2rem; justify-content: center;
    margin-top: .35rem; }
  .picks label { font: .6rem/1 var(--mono); color: var(--dim); cursor: pointer;
    border: 1px solid var(--rule); border-radius: 2px; padding: .18rem .4rem; }
  .picks label:hover { border-color: var(--rule-strong); color: var(--ink); }
  .steps input:focus-visible ~ .picks { outline: 1px dashed var(--rule-strong);
    outline-offset: 3px; }
""" & SWITCHING & """  </style>"""

  let sheet = HEAD & """<div class="wrap">
  <h1>Frame positions, drawn</h1>
  <p class="lede">Every position this project draws today, in one place, so each
  can be kept or dropped. Each card carries the identifier to quote back.</p>
  <p class="tally">{{tally}}</p>
  <p class="how"><b>How to read it.</b> Section A is the standard diagram and is
  complete at sixteen. Sections B and C are drawn by a different chain entirely
  &mdash; they take a pose, arm levels and a fractional wind, none of which the
  standard diagram can say. Nothing in A knows what level an arm is held at.</p>
  """ & body & "</div>"

  # Counted off page itself rather than tallied while building it, so
  # count cannot drift from what is drawn.
  let
    seen = sheet.count("""<figure class="pic""")
    tally = &"""<b>{KEPT.len}</b> kept &middot; <b>{DROPPED.len}</b> dropped """ &
      &"""&middot; <b>{FLAWED.len}</b> marked for a mend &middot; """ &
      &"""<b>{seen - KEPT.len - DROPPED.len}</b> still to rule on, of {seen}."""
  sheet.replace("{{tally}}", tally)


func render*(P: Parts): string =
  ## Lay page out under its own title.
  document("Frame Positions, Drawn", sheetOf(P))


func drawingOf(html, id: string): string =
  ## Cut this card's drawings back out of built page, joined as card holds
  ## them.
  ##   Card opens with its own `figure`, so its slice runs from last of
  ##     those before its identifier up to identifier itself.
  ##   Cell that switches between several drawings carries all of them, and
  ##     verdict on cell is verdict on all, so pin covers all.
  const CELL = """<figure class="pic"""
  let
    marks = &"<code>{id}</code>"
    names = html.find(marks)
  doAssert names > 0, &"A ruled card is not on the page: got `{id}`."
  let opens = html.rfind(CELL, last = names)
  doAssert opens >= 0, &"A ruled card has no cell of its own: got `{id}`."
  var at = opens
  while true:
    let starts = html.find("<svg", at)
    if starts < 0 or starts > names:
      break
    let shuts = html.find("</svg>", starts)
    if shuts < 0:
      break
    result.add html[starts .. shuts + "</svg>".len - 1]
    at = shuts + 1


func pinsIn*(html: string): string =
  ## Read back what every card on this page is drawn as, as `review.pins`
  ## holds it.
  ##   Read off page rather than kept while building it, so what is pinned
  ##     is what was published and nothing beside it.
  var held = newJObject()
  for id in KEPT:
    held[id] = %($hash(drawingOf(html, id)))
  for id in DROPPED:
    held[id] = %($hash(drawingOf(html, id)))
  held.pretty & "\n"
