## Lay out every frame position this project draws, card by card, for
## Architect to rule on.
##
##   Page exists to be argued with: each card carries identifier to quote
##     back, and mark saying whether it has been kept, dropped, or sent back
##     for mend.  Unmarked is unreviewed, never approved.
##   Verdict is given on picture, not on identifier.  So every ruled card's
##     drawing is pinned in `review.pins`, and build refuses to write page
##     whose ruled card has moved since: mend that reaches further than it
##     meant to stops here rather than shipping approval nobody gave.
##     Pins are regenerated by `tools/build.nim pins`, which is deliberate
##       second step -- verdict and pin are added together or not at all.
##   Sections `A` and `B` come from tables workbench already builds; `C` and
##     `D` are drawn here, and are only place project draws crossed pair's chain.

{.experimental: "strictFuncs".}

import std/[hashes, json, options, sequtils, strformat, strutils, tables]

import ./[page, parts]
import ../src/dance_ontology
import ../src/dance_ontology/draw/[figure, terms]


const PINS = staticRead("review-pins.json")
  ## What every ruled card's drawing was when it was ruled on.

const MODELLED = staticRead("modelled.json")
  ## Which cards body sim reaches, written by `design/modelled`.
  ##   Second tag each cell carries.  `kept` is Architect's, by eye on floor;
  ##     `modelled` is sim's answer confirmed by Architect against their own body,
  ##     and goal is both at hundred per cent.  Sim reaching card is not enough:
  ##     Architect, on seeing sim's stills laid beside reference: many static
  ##     states are wrong; mark everything unmodelled until confirmed.  So card
  ##     sim reaches reads *unconfirmed* until its name is in `CONFIRMED`, and
  ##     only then *modelled*.
  ##   Card sim has not been asked about is absent, and gets no tag: unasked
  ##     reads as unasked rather than as disagreement.

const pinned = block:
  var held: Table[string, string]
  for pair in PINS.parseJson.pairs:
    held[pair.key] = pair.val.getStr
  held

const modelled = block:
  var said: Table[string, bool]
  for pair in MODELLED.parseJson.pairs:
    said[pair.key] = pair.val.getBool
  said

const
  KEPT = ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10",
          "A11", "A12", "A13", "A14", "A15", "A16", "A17",
          "B1", "B2", "B3", "B4", "B5", "B6", "B7",
          "B8", "B9", "B10", "B11", "B12", "B13", "B14",
          "B15", "B16", "B17", "B18", "B19", "B20", "B21",
          "B22", "B23", "B24", "B25", "B26", "B27", "B28",
          # C1, C7, D1, D7 are swans, and their straight connection crosses
          # close to hand.  Break there was left off, which drew
          # that connection detached from its hand; it is drawn now, so
          # they go back to unruled rather than carry verdict given on
          # picture that has since moved.
          "C1", "C2", "C3", "C4", "C5", "C6", "C7",
          "D1", "D2", "D3", "D4", "D5", "D6", "D7",
          "E1", "E2", "E3", "E4", "E5", "E6", "E7", "E8",
          "E9", "E10", "E11", "E12", "E13", "E14", "E15", "E16",
          "E17", "E18", "E19", "E20", "E21", "E22", "E23", "E24",
          "E25", "E26", "E27", "E28", "E29", "E30", "E31", "E32",
          "F1", "F2"]
    ## Ids Architect has confirmed accurate.  Added as they are ruled on.
  DROPPED: seq[string] = @[]
    ## Ids Architect has ruled out.
  CONFIRMED: seq[string] = @[]
    ## Ids whose sim still Architect has confirmed against their own body, on
    ## viewer page that lays each beside its cell.  Added as they are confirmed,
    ## none yet.  Confirmation is of one still; when sim's still of confirmed
    ## cell moves, its name comes out of here until it is confirmed again.
  FLAWED = initTable[string, string]()
    ## Position is right, drawing is not: kept, with what to mend.

func esc(s: string): string =
  s.multiReplace(("&", "&amp;"), ("<", "&lt;"), (">", "&gt;"))

const
  MANNER_SAID = {"fa": "follow turns", "la": "lead turns",
              "fo": "follow orbits", "lo": "lead orbits"}.toTable
    ## Workbench's tags said in words, since sheet is read by eye.
  QUARTER_SAID = ["none", "a quarter", "a half", "three quarters"]
    ## How far round that manner has gone, counted in quarter turns.
  QUARTER_FROM = ["the start", "a quarter", "a half", "three quarters"]
    ## Same, worded for move that sets off from it.

const QUARTER_WAY = wayName(wayOf(HalfTurns(QUARTER)))
  ## Which way round every quarter on this page turns.
  ##   Read off turn itself rather than written down, so label cannot
  ##     outlive sign it describes.

func said(tag: string; quarter: int): string =
  ## Name one manner of turn, how far it has gone, and which way round.
  if quarter == 0: &"{MANNER_SAID[tag]} {QUARTER_SAID[quarter]}"
  else: &"{MANNER_SAID[tag]} {QUARTER_SAID[quarter]} {QUARTER_WAY}"

func unpinned(svg: string): string =
  ## Take off pixel size workbench pins each figure to for its own rows, so
  ## card decides how big picture is drawn: inline style would beat sheet.
  result = svg
  const OPEN = " style=\"width: "
  let at = result.find(OPEN)
  if at < 0:
    return
  let shut = result.find('"', at + OPEN.len)
  if shut < 0:
    return
  result = result[0 ..< at] & result[shut + 1 .. ^1]

proc checkReview*() =
  ## Check every card ruled on has pin holding it to what it was drawn as.
  ##   Verdict without pin is verdict nothing guards, which is how ruled
  ##     card came to move under one in first place.
  for id in KEPT:
    doAssert id in pinned,
      &"A kept card carries no pin; run `tools/build.nim pins`: got `{id}`."
  for id in DROPPED:
    doAssert id in pinned,
      &"A dropped card carries no pin; run `tools/build.nim pins`: got `{id}`."


func reviewParts*(single, hand: Parts): Parts =
  ## Collect every figure this page places: both walked pages' own parts,
  ## which it draws again at its own size, and crossed pair's.
  ##   Walked pages' parts are handed in, as their pages built them, rather
  ##     than routed again here.
  result = single
  for key, svg in hand:
    result[key] = svg
  for key, svg in pairTurnParts():
    result[key] = svg


func sheetOf(P: Parts): string =
  ## Build page, holding every card already ruled on to its own pin.

  func stepped(id: string; steps: seq[tuple[pick, note, svg: string]];
               asks: seq[string] = @[]): string =
    ## Stack several drawings in one cell, one shown at time, with button
    ## apiece.
    ##   Each step carries sim's own tag, not cell.  Cell that folds six edges
    ##     together and is marked by worst of them paints five reachable edges
    ##     red for sake of sixth, and reader asking why easy one is refused is
    ##     reading tag that was never about it.
    ##   Radio button and sibling rule do switching, so cell needs no script:
    ##     page stays markup browser can draw with nothing running.
    ##   Every step keeps its own note under its own picture, since note is
    ##     what tells one step from next.
    var
      picks = ""
      frames = ""
      buttons = ""
    for i, step in steps:
      let at = &"{id}-{i + 1}"
      picks.add &"""<input type="radio" name="{id}" id="{at}""" &
        (if i == 0: "\" checked>" else: "\">")
      let says = if i >= asks.len or asks[i] notin modelled: ""
                 elif not modelled[asks[i]]: """<em class="tag nomodel">not modelled</em>"""
                 elif id in CONFIRMED: """<em class="tag model">modelled</em>"""
                 else: """<em class="tag unsure">unconfirmed</em>"""
      frames.add &"""<div>{unpinned(step.svg)}{says}""" &
        &"""<span class="step">{esc(step.note)}</span></div>"""
      buttons.add &"""<label for="{at}">{esc(step.pick)}</label>"""
    &"""{picks}<div class="frames">{frames}</div>""" &
      &"""<div class="picks">{buttons}</div>"""

  func card(id, label, note, art: string; drawings: seq[string];
            switching = false; asks: seq[string] = @[]): string =
    ## Set one cell beside its identifier, carrying whatever has been ruled
    ## on it.  Unmarked is unreviewed, not approved.
    let
      flawed = id in FLAWED
      kept = id in KEPT
      dropped = id in DROPPED
      mark = if flawed: " flawed" elif kept: " kept"
             elif dropped: " dropped" else: ""
      badge = if flawed: """<em class="tag mend">mend</em>"""
              elif kept: """<em class="tag keep">kept</em>"""
              elif dropped: """<em class="tag drop">drop</em>"""
              else: ""
      # Sim's own tag, drawn outlined where Architect's is solid, so ruling by
      # eye and reading by engine are never taken for one another.  It sits in
      # other corner, and outside drawing, so no pin moves by its being here.
      # Cell folding several pictures together stands for several questions, and
      # is reached only where sim reaches every one of them.  Card nothing has
      # been asked about carries no tag at all.
      put = if asks.len > 0: asks else: @[id]
      known = put.filterIt(it in modelled)
      reached = known.len > 0 and known.allIt(modelled[it])
      # Cell's own colour says how far it has got: green only where it is kept,
      # wholly reached and confirmed; amber where sim reaches all or part of it
      # and Architect has not yet confirmed; red where sim reaches none of it.
      # Badges keep saying which of two tags each is.
      stand = if known.len == 0: ""
              elif reached and id in CONFIRMED: " met"
              elif reached or known.anyIt(modelled[it]): " part"
              else: " unmet"
      says = if switching or known.len == 0: ""
             elif not reached: """<em class="tag nomodel">not modelled</em>"""
             elif id in CONFIRMED: """<em class="tag model">modelled</em>"""
             else: """<em class="tag unsure">unconfirmed</em>"""
    # Questions cell stands for are written on it, so viewer page laying sim
    # beside each cell can find its still by question and not by cell's name.
    # Verdict was given on pictures, so picture that moved under one carries
    # approval it was never given.  Card holds itself to what it was drawn
    # as when it was ruled on, and mend reaching further than it meant to
    # stops here rather than shipping.  Cell holding several drawings is
    # held to all of them, since verdict on it is verdict on all.
    if kept or dropped:
      doAssert $hash(drawings.join("")) == pinned.getOrDefault(id),
        &"A card already ruled on has been re-drawn: `{id}`.  Either the " &
          "mend is too wide, or that verdict has to go back."
    &"""<figure class="pic{mark}{stand}" data-asks="{put.join(" ")}"><div class="art""" &
    (if switching: " steps" else: "") & &"""">{art}{badge}{says}</div>""" &
    &"""<figcaption><code>{esc(id)}</code><b>{esc(label)}</b>""" &
    (if note.len > 0: &"""<span>{esc(note)}</span>""" else: "") &
    (if flawed: &"""<span class="fix">{esc(FLAWED[id])}</span>""" else: "") &
    "</figcaption></figure>"

  func card(id, label, note, svg: string; asks: seq[string] = @[]): string =
    ## Set one drawing in cell of its own.
    card(id, label, note, unpinned(svg), @[unpinned(svg)], asks = asks)

  func card(id, label, note: string;
            steps: seq[tuple[pick, note, svg: string]];
            asks: seq[string] = @[]): string =
    ## Set several drawings in one cell, switched between by button.
    card(id, label, note, stepped(id, steps, asks),
         steps.mapIt(unpinned(it.svg)), switching = true, asks = asks)

  var body = ""

  # `A`. Standard diagram: eight frames, two twist parities, and that is all of it.
  body.add """<section id="standard"><h2>A &middot; The standard diagram</h2>
  <p class="lede">Every drawing in this project is one of these, and a table built at compile
  time holds them all. The drawing reads the frame hold, the parity of the twist, and the way
  the couple turned. It never reads the level of an arm, and it never reads contact.</p>
  <p class="how"><b>The diagram cannot name the facing.</b> The model holds eight facings, which
  take three bits. The diagram draws only half turns, which reach four of them, and it reads one
  bit: the parity of the twist. So the drawing commits to one facing of each pair: it turns the
  follow, and never the lead. Every card below names the facing it draws, and not the facing the
  model knows.</p>
  <p class="how"><b>Each frame counts from its own rest.</b> Rest is the facing where the
  connections of that hold run parallel and cross nothing. A same-name pair rests <b>Pillion</b>
  rather than Face-to-face. So A10 and A12 read <i>at rest</i>, and A9 and A11 read <i>half a turn
  from Pillion</i>. A card names a way round only where the other way
  round draws a different picture, which is A16 and A17 alone.</p>
  <p class="how"><b>A crossing breaks at the arm that goes under.</b> The drawing cuts that
  arm at the middle, and the <code>over</code> field of the frame says which arm it is. A16
  carries no such field: its two connections run parallel at rest, and they cross only once
  the follow turns. Which arm ends over depends on the way the follow turned, so A16 and A17 draw
  the two ways. They are the one frame of the eight where the way round changes the
  picture.</p><div class="grid">"""
  func armFor(side: Side): Arm =
    ## Say which drawn arm this side of lead is.
    if side == Side.Left: Arm.L else: Arm.R

  func armFor(site: Site): Arm =
    ## Same for hand of follow.
    if site == Site.LeftHand: Arm.L else: Arm.R

  func restsFacing(target: Frame): bool =
    ## Say whether this frame rests Face-to-face rather than Pillion.
    ##   Hold rests where its two connections run parallel and cross
    ## nothing, which for same-name pair is Pillion and not Face-to-
    ##     face (rule 31).  Measured by `phaseOf`, never written down.
    ##   Hold with fewer than two connections has no such state to be at, so
    ##     it is counted from face to face like everything else.
    if target.countHolds < 2:
      return true
    var holds: Holds
    for side in Side:
      if target.hold[side].isSome:
        holds[armFor(side)] = some armFor(target.hold[side].get)
    phaseOf(holds) < 1e-9

  proc facingNote(target: Frame; twist: int; way: string): string =
    ## Say which facing this picture draws, and what it is turned from.
    let
      drawn = if twist == 0: "Face-to-face" else: "Pillion"
      rest = if restsFacing(target): "Face-to-face" else: "Pillion"
    if drawn == rest: &"{drawn}, at rest"
    elif way.len > 0: &"{drawn}, half a turn {way} from {rest}"
    else: &"{drawn}, half a turn from {rest}"

  func turnShows(target: Frame): bool =
    ## Say whether turning one way draws anything other way does not.
    renderFrame(target, HalfTurns(1)) != renderFrame(target, HalfTurns(-1))

  for i, target in FRAMES:
    for twist in [0, 1]:
      let way = if twist == 1 and turnShows(target): "clockwise" else: ""
      body.add card(&"A{i * 2 + twist + 1}", describe(target),
                    facingNote(target, twist, way),
                    renderFrame(target, HalfTurns(twist)))
  # And other way round, wherever turning that way draws different picture.
  # Appended rather than interleaved, so every identifier already ruled on
  # still names picture it was ruled on.
  var also = FRAMES.len * 2
  for target in FRAMES:
    let widdershins = renderFrame(target, HalfTurns(-1))
    if widdershins == renderFrame(target, HalfTurns(1)):
      continue
    inc also
    body.add card(&"A{also}", describe(target),
                  facingNote(target, 1, "anticlockwise"), widdershins)
  body.add "</div></section>"

  # `B`. Single-hand turns: what animated page walks through.
  let st = P
  body.add """<section id="single"><h2>B &middot; Single-hand turn positions</h2>
  <p class="lede">These are the positions that the single-hand turns page walks between. Two
  manners of one family stand at the same four positions, and manners of two families meet
  where they rest. So every repeat folds into one card, and each card names the manners and
  the quarters that land on it. Two manners are axis turns, one of the follow and one of the
  lead. Two are orbits, the follow round the lead and the lead round the follow. A quarter
  says how far round that manner has gone.</p>"""
  var n = 0
  for c in 0 ..< SINGLES.len:
    body.add &"""<h3>{esc(SINGLES[c].name)}</h3><div class="grid wide">"""
    var seen = initTable[string, string]()   # svg -> id already given it
    var order: seq[string]
    var whose = initTable[string, seq[string]]()
    var asked = initTable[string, seq[string]]()  # svg -> questions it stands for
    for manner in Manner:
      for q in 0 ..< QUARTERS_ROUND:
        let key = &"st_{MANNERS[manner].tag}_{c}_{q}"
        if key notin st: continue
        let svg = st[key]
        if svg notin seen:
          inc n
          seen[svg] = &"B{n}"
          order.add svg
        whose.mgetOrPut(svg, @[]).add said(MANNERS[manner].tag, q)
        asked.mgetOrPut(svg, @[]).add &"st_{MANNERS[manner].tag}_{c}_{q}"
    for svg in order:
      # Where every manner lands on one picture, say so once rather than four times.
      let who = if whose[svg].len == MANNERS.len and
                   QUARTER_SAID[0] in whose[svg][0]: "every manner, before it starts"
                else: whose[svg].join(" \u00B7 ")
      body.add card(seen[svg], SINGLES[c].name, who, svg, asks = asked[svg])
    body.add "</div>"
  body.add "</section>"

  func windNote(note: string; wind: float; zero = ""): string =
    ## Say how far position stands from where its chain rests, and which way
    ## round.
    ##   Way comes from `wayOf`, so page and vocabulary cannot drift apart on
    ##     which sign is which.
    ##   `zero` replaces resting note for chain whose rest is not app's frame,
    ##     which `chainFor` names for hand-to-hand chain it was written for.
    if abs(wind) < 1e-9: (if zero.len > 0: zero else: note)
    else: note & " " & wayName(wayOf(HalfTurns(wind * 2)))


  # `C`. Chain two-hand page walks.
  let hh = P
  const PAIRED: Holds = [some Arm.L, some Arm.R]
  let
    dualPhase = phaseOf(PAIRED)
    dualChain = chainFor(PAIRED)
  # One scale for both chains, so section `C` and section `D` compare directly.
  var half = 0.0
  for position in CHAIN:
    half = max(half, extent(handPose(position.wind), captions = false))
  for position in dualChain:
    half = max(half, extent(posedAt(position.wind, dualPhase), captions = false))

  body.add """<section id="chain"><h2>C &middot; The cross-name chain, Face-to-face at rest</h2>
  <p class="lede">The chain stands in seven places, half a turn apart, and the hand-to-hand page
  walks along it. Each place carries a twist as a real number rather than a count of half turns,
  which the standard diagram cannot hold. The facing alternates along the chain: Face-to-face at
  the whole turns, and Pillion at the halves. Every caption says how far round the place
  stands from the frame, <b>clockwise seen from above</b>. That is how the drawings see the
  couple, and it names one turn whichever dancer walks it. Section D is drawn at this scale, so
  the two chains stand against each other.</p><div class="grid wide">"""
  for i, position in CHAIN:
    body.add card(&"C{i + 1}", position.name, windNote(position.note, position.wind),
      renderFigure("tiny", HAND_TO_HAND, ABOVE_BOTH, captions = false,
        pose = some handPose(position.wind), half = some half,
        twist = windTwist(position.wind), clear_marks = true))
  body.add "</div></section>"


  # `D`. Dual chain: same hold, follow starting away.
  body.add &"""<section id="paired"><h2>D &middot; The same-name chain, Pillion at rest</h2>
  <p class="lede">This hold joins the left of the lead to the left of the follow, and right to
  right. It walks the chain of section C, read half a turn along. So it runs parallel
  <b>Pillion</b> rather than Face-to-face, and its phase measures {dualPhase} where the phase of
  the other chain measures {HAND_PHASE}. Its facing alternates the other way about: Pillion at the
  whole turns, and Face-to-face at the halves. No page in this project walks this
  chain.</p><div class="grid wide">"""
  for i, position in dualChain:
    body.add card(&"D{i + 1}", position.name,
      windNote(position.note, position.wind,
             zero = "this hold's own parallel state"),
      renderFigure("tiny", PAIRED, ABOVE_BOTH, captions = false,
        pose = some posedAt(position.wind, dualPhase), half = some half,
        twist = windTwist(position.wind), clear_marks = true))
  body.add "</div></section>"

  # `E`. Every single-hand turn animated, edge by edge.
  body.add """<section id="single-moving"><h2>E &middot; Single-hand turns, moving</h2>
  <p class="lede">Every edge of section B, walked by every manner of turn. Each manner of each hold
  takes <b>two cells</b>. One is the whole round in one figure. The other is the same round a
  quarter at a time, with a button for each quarter.</p>
  <p class="lede">Both run at one pace, so
  the loop of the round is four times the loop of an edge. No two of these walks draw one picture,
  even where two of them
  start and end alike. The turn of the lead is told in two stages, as rule 18 asks.</p>
  <p class="how"><b>Every walk here turns one way.</b> The page turns by a positive quarter, so
  every walk here is clockwise. The positions in section B are complete either way, because
  four quarters make a whole round. <b>The anticlockwise walks are not drawn</b>, and neither
  is any edge run backwards. That is a gap in this reference, and not in the model.</p>
  <p class="how"><b>The bend at a chevron is a fault here, and nowhere above.</b> A reach keeps
  clear of both chevrons, so that a line through a chevron always means that hand is held. Rule
  22 holds it off, and every still in section B is right because of it. <b>In a walk the same
  rule makes the motion catch</b>: the reach steps round a chevron as it passes, then snaps
  back. The stills stand as they are drawn, and the mend belongs to the walk.</p>"""
  var m = 0
  for c in 0 ..< SINGLES.len:
    body.add &"""<h3>{esc(SINGLES[c].name)}</h3><div class="grid wide">"""
    for manner in Manner:
      let
        tag = MANNERS[manner].tag
        said = &"{MANNER_SAID[tag]} {QUARTER_WAY}"
      if &"rd_{tag}_{c}" in st:
        inc m
        body.add card(&"E{m}", said, "the whole round, four quarters in one",
                      st[&"rd_{tag}_{c}"], asks = @[&"rd_{tag}_{c}"])
      var
        steps: seq[tuple[pick, note, svg: string]]
        asksE: seq[string]
      for q in 0 ..< QUARTERS_ROUND:
        let key = &"tr_{tag}_{c}_{q}_{(q + 1) mod QUARTERS_ROUND}"
        if key notin st: continue
        asksE.add key
        steps.add ($(q + 1),
          &"quarter {q + 1} of 4: from {QUARTER_FROM[q]} to " &
            &"{QUARTER_FROM[(q + 1) mod QUARTERS_ROUND]}",
          st[key])
      if steps.len > 0:
        inc m
        body.add card(&"E{m}", said, "one quarter at a time", steps,
                      asks = asksE)
    body.add "</div>"
  body.add "</section>"

  func chainWay(manner: Manner): string =
    ## Say which way round this manner of turn walks chain.
    ##   Not same for all four: positive turn by lead unwinds what positive
    ##     turn by follow winds (rule 30), so each manner turns whichever way
    ##     carries pair inward along chain, and that sense is measured.
    wayName(wayOf(HalfTurns(HALF * windSense(manner))))


  # `F`. Every chain edge animated.
  body.add """<section id="chain-moving"><h2>F &middot; The cross-name chain, moving</h2>
  <p class="lede">Every edge of section C, walked by every manner of turn. Each manner takes <b>two
  cells</b>. One is the whole chain in one figure. The other is the same chain an edge at a time,
  with a button for each edge.</p>
  <p class="lede">The chain has ends and cannot close on itself,
  so the whole figure runs out from one swan to the other and back. All four manners walk the same
  chain, because an
  orbit winds the pair as far as it carries the walker. <b>They do not all turn the same way
  round</b>: a positive turn by the lead unwinds what a positive turn by the follow winds. So
  each manner turns the way that carries the pair along the chain, and every caption names that
  way, measured on the build.</p><div class="grid wide">"""
  var k = 0
  for manner in Manner:
    let
      tag = MANNERS[manner].tag
      said = &"{MANNER_SAID[tag]} {chainWay(manner)}"
    if &"hc_{tag}" in hh:
      inc k
      body.add card(&"F{k}", said,
                    &"the whole chain, {CHAIN.len - 1} halves out and back",
                    hh[&"hc_{tag}"], asks = @[&"hc_{tag}"])
    var
      steps: seq[tuple[pick, note, svg: string]]
      asksF: seq[string]
    for i in 0 ..< CHAIN.len - 1:
      let key = &"hw_{tag}_{i}"
      if key notin hh: continue
      asksF.add key
      steps.add ($(i + 1), CHAIN[i].name & " to " & CHAIN[i + 1].name, hh[key])
    if steps.len > 0:
      inc k
      body.add card(&"F{k}", said, "one edge at a time", steps, asks = asksF)
  body.add "</div></section>"

  # `G`. Every edge of paired chain animated, as `F` does for section C.
  body.add &"""<section id="paired-moving">
  <h2>G &middot; Hand-to-hand chain, Pillion, moving</h2>
  <p class="lede">Every edge of the same-name chain of section D, walked by every manner of
  turn. Each manner takes the same two cells that section F uses, and the way each manner walks
  is read the same. This chain rests <b>Pillion</b> rather than Face-to-face, because Face-to-face
  its two connections lie through each other (rule 31). Its phase measures
  {dualPhase}, where the phase of the cross-name chain measures {HAND_PHASE}.</p>
  <div class="grid wide">"""
  var g = 0
  for manner in Manner:
    let
      tag = MANNERS[manner].tag
      said = &"{MANNER_SAID[tag]} {chainWay(manner)}"
    if &"pc_{tag}" in hh:
      inc g
      body.add card(&"G{g}", said,
                    &"the whole chain, {dualChain.len - 1} halves out and back",
                    hh[&"pc_{tag}"], asks = @[&"pc_{tag}"])
    var
      steps: seq[tuple[pick, note, svg: string]]
      asksG: seq[string]
    for i in 0 ..< dualChain.len - 1:
      let key = &"pw_{tag}_{i}"
      if key notin hh: continue
      asksG.add key
      steps.add ($(i + 1),
                 dualChain[i].name & " to " & dualChain[i + 1].name, hh[key])
    if steps.len > 0:
      inc g
      body.add card(&"G{g}", said, "one edge at a time", steps, asks = asksG)
  body.add "</div></section>"

  const SWITCHING = block:
    ## Rules that show one step of switching cell and light its button.
    ##   Written out per step rather than by script: page is markup browser
    ##     draws with nothing running, and it stays that way.
    ##   Count follows longest walk on page, so cell of six steps cannot
    ##     quietly lose its last one.
    var css = ""
    for i in 1 .. max(QUARTERS_ROUND, CHAIN.len - 1):
      css.add &"  .steps input:nth-of-type({i}):checked ~ .frames > " &
        &"div:nth-child({i}) {{ display: block; }}\n"
      css.add &"  .steps input:nth-of-type({i}):checked ~ .picks > " &
        &"label:nth-child({i}) {{ background: var(--ink);" &
        " color: var(--card); border-color: var(--ink); }\n"
    css

  const HEAD = """<style>
  :root { --keep: #3f7550; --keep-wash: #eef4f0; --drop: #b3392a;
    --drop-wash: #f8efed; --mend: #a06a1e; --mend-wash: #f7f1e6;
    --mend-ink: #7a5016; }
  @media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) {
    --keep: #6cab80; --keep-wash: #1a2420; --drop: #e8705e;
    --drop-wash: #291c1a; --mend: #d9a45a; --mend-wash: #26200f;
    --mend-ink: #d7ab63; } }
  :root[data-theme="dark"] { --keep: #6cab80; --keep-wash: #1a2420;
    --drop: #e8705e; --drop-wash: #291c1a; --mend: #d9a45a;
    --mend-wash: #26200f; --mend-ink: #d7ab63; }
  .wrap { max-width: 72rem; margin: 0 auto; }
  .lede { color: var(--dim); max-width: 44rem; }
  .grid { display: grid; gap: .6rem; margin: 1rem 0 1.6rem;
    grid-template-columns: repeat(auto-fill, minmax(9.5rem, 1fr)); }
  .grid.wide { grid-template-columns: repeat(auto-fill, minmax(15rem, 1fr)); }
  .pic { margin: 0; background: var(--card); border: 1px solid var(--rule);
    border-radius: 3px; padding: .5rem; display: flex; flex-direction: column;
    gap: .4rem; }
  .pic .art { display: block; }
  .pic svg, .pic svg.tiny, .pic svg.mv { display: block; width: 100%;
    height: auto; }
  .pic figcaption { display: flex; flex-direction: column; gap: .1rem;
    font: .7rem/1.35 var(--sans); border-top: 1px solid var(--rule);
    padding-top: .35rem; }
  .pic code { font: .64rem var(--mono); color: var(--faint);
    letter-spacing: .04em; }
  .pic b { font-weight: 600; color: var(--ink); }
  .pic span { color: var(--dim); font: .64rem/1.3 var(--mono); }
  h2 { font-size: 1.05rem; letter-spacing: .01em; margin: 2.2rem 0 .3rem;
    padding-top: 1.1rem; border-top: 2px solid var(--rule-strong); }
  h3 { font-size: .78rem; text-transform: uppercase; letter-spacing: .1em;
    color: var(--faint); margin: 1.2rem 0 0; font-weight: 600; }
  h1 { font-size: 1.5rem; margin: 0 0 .3rem; }
  .how { background: var(--wash); border-left: 3px solid var(--rule-strong);
    padding: .8rem 1rem; margin: 1.2rem 0 0; max-width: 44rem;
    font-size: .88rem; color: var(--dim); }
  .how b { color: var(--ink); }
  .tally { font: .82rem var(--mono); color: var(--dim); margin: .6rem 0 0; }
  .tally b { color: var(--ink); }
  .pic .art { position: relative; }
  .tag { position: absolute; top: 0; right: 0; font: 600 .58rem/1 var(--sans);
    text-transform: uppercase; letter-spacing: .08em; padding: .2rem .3rem;
    border-radius: 2px; font-style: normal; }
  .tag.keep { background: var(--keep); color: var(--card); }
  .tag.drop { background: var(--drop); color: var(--card); }
  /* Cell is green only where Architect kept it *and* sim reaches all of it.
     Kept alone coloured nothing: it was page's one colour and said nothing of
     second tag, so page read finished wherever verdict was given. */
  .pic.part { border-color: var(--mend); background: var(--mend-wash); }
  .pic.unmet { border-color: var(--drop); background: var(--drop-wash); }
  .pic.kept.met { border-color: var(--keep); background: var(--keep-wash); }
  .pic.dropped { border-color: var(--drop); background: var(--drop-wash); }
  .pic.dropped .art svg { opacity: .38; }
  .tag.mend { background: var(--mend); color: var(--card); }
  .tag.model, .tag.nomodel, .tag.unsure { right: auto; left: 0;
    background: var(--card); }
  .tag.unsure { color: var(--mend-ink); border: 1px solid var(--mend); }
  .tag.model { color: var(--keep); border: 1px solid var(--keep); }
  .tag.nomodel { color: var(--drop); border: 1px solid var(--drop); }
  .pic.flawed { border-color: var(--mend); background: var(--mend-wash); }
  .pic .fix { color: var(--mend-ink); font: .62rem/1.35 var(--sans); }
  .pic { overflow: hidden; }
  .steps > input { position: absolute; width: 1px; height: 1px; opacity: 0; }
  .frames > div { display: none; position: relative; }
  .frames span.step { display: block; color: var(--dim); margin-top: .25rem;
    font: .6rem/1.3 var(--mono); }
  .picks { display: flex; flex-wrap: wrap; gap: .2rem; justify-content: center;
    margin-top: .35rem; }
  .picks label { font: .6rem/1 var(--mono); color: var(--dim); cursor: pointer;
    border: 1px solid var(--rule); border-radius: 2px; padding: .18rem .4rem; }
  .picks label:hover { border-color: var(--rule-strong); color: var(--ink); }
  .steps input:focus-visible ~ .picks { outline: 1px dashed var(--rule-strong);
    outline-offset: 3px; }
""" & SWITCHING & """  </style>"""

  let sheet = HEAD & """<div class="wrap">
  <h1>Frame positions, drawn</h1>
  <p class="lede">Every position this project draws, in one place, so that the Architect
  can keep or drop each one. Every card carries an identifier to quote back.</p>
  <p class="tally">{{tally}}</p>
  <p class="how"><b>How to read it.</b> Section A is the standard diagram. It is a table of
  frames, and it says no level at all. Sections B to D come from another chain. That chain takes a
  pose, a level for each arm, and a twist that is not a count of half turns.</p>
  <p class="how"><b>Every cell carries two tags.</b> <i>Kept</i> is the ruling of the Architect
  on the drawing, by eye on the floor.</p>
   <p class="how">The other tag is the body sim's. It reads <i>not modelled</i>
  where the sim reaches no pose. It reads <i>unconfirmed</i> where the sim reaches one that the
  Architect has not yet held against their own body on the viewer. It reads <i>modelled</i>
  once they have. A pose the sim reaches is a claim, and never a verdict.</p>
  """ & body & "</div>"

  # Counted off page itself rather than tallied while building it, so
  # count cannot drift from what is drawn.
  let
    seen = sheet.count("""<figure class="pic""")
    unsure = sheet.count("""<em class="tag unsure">""")
    tally = &"""<b>{KEPT.len}</b> kept &middot; <b>{DROPPED.len}</b> dropped """ &
      &"""&middot; <b>{FLAWED.len}</b> marked for a mend &middot; """ &
      &"""<b>{seen - KEPT.len - DROPPED.len}</b> still to rule on, of {seen}. """ &
      &"""Against the model: <b>{CONFIRMED.len}</b> confirmed by the Architect, """ &
      &"""<b>{unsure}</b> reached by the sim and not yet confirmed."""
  sheet.replace("{{tally}}", tally)


func render*(P: Parts): string =
  ## Lay page out under its own title.
  document("Frame Positions, Drawn", sheetOf(P))


func drawingOf(html, id: string): string =
  ## Cut this card's drawings back out of built page, joined as card holds
  ## them.
  ##   Card opens with its own `figure`, so its slice runs from last of
  ##     those before its identifier up to identifier itself.
  ##   Cell that switches between several drawings carries all of them, and
  ##     verdict on cell is verdict on all, so pin covers all.
  const CELL = """<figure class="pic"""
  let
    marks = &"<code>{id}</code>"
    names = html.find(marks)
  doAssert names > 0, &"A ruled card is not on the page: got `{id}`."
  let opens = html.rfind(CELL, last = names)
  doAssert opens >= 0, &"A ruled card has no cell of its own: got `{id}`."
  var at = opens
  while true:
    let starts = html.find("<svg", at)
    if starts < 0 or starts > names:
      break
    let shuts = html.find("</svg>", starts)
    if shuts < 0:
      break
    result.add html[starts .. shuts + "</svg>".len - 1]
    at = shuts + 1


func pinsIn*(html: string): string =
  ## Read back what every card on this page is drawn as, as `review.pins`
  ## holds it.
  ##   Read off page rather than kept while building it, so what is pinned
  ##     is what was published and nothing beside it.
  var held = newJObject()
  for id in KEPT:
    held[id] = %($hash(drawingOf(html, id)))
  for id in DROPPED:
    held[id] = %($hash(drawingOf(html, id)))
  held.pretty & "\n"
